'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import type { DemoCaseStep } from '@/lib/demo/merchantCaseV1';
import { parseRequestedPlanId, PLANS, PUBLIC_PLAN_IDS } from '@/lib/billing/plans';
import { replaceHistoryUrlIfChanged } from '@/lib/navigation/history';
import { formatNumber } from '@/lib/utils/format';

const sans = "'Inter',sans-serif";
const mono = "'IBM Plex Mono',monospace";
const ink = '#1c1f23';
const muted = '#64686d';
const faint = '#6f6a63';
const line = '#eae8e5';

function PublicHeader({ synthetic = false }: { synthetic?: boolean }) {
  return <header style={{ minHeight: 62, display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: '12px 20px', padding: '12px clamp(16px,3vw,40px)', borderBottom: `1px solid ${line}` }}>
    <Link href="/landing" style={{ display: 'flex', alignItems: 'center', gap: 9, color: ink, textDecoration: 'none' }}><span style={{ width: 24, height: 24, display: 'grid', placeItems: 'center', borderRadius: 8, background: ink, color: '#fff', font: `500 12px/1 ${mono}` }}>∅</span><strong>Unauth</strong></Link>
    {synthetic ? <span style={{ padding: '3px 8px', borderRadius: 6, background: '#fff3e9', color: '#7a5310', font: `500 10px/1.5 ${sans}`, letterSpacing: '.05em' }}>SYNTHETIC DATA · NOBODY&apos;S REAL ORDER</span> : null}
    <span style={{ flex: 1 }} /><Link href="/pricing" style={navStyle}>Pricing</Link><Link href={synthetic ? '/landing' : '/demo'} style={navStyle}>{synthetic ? 'Back to the site' : 'See it work'}</Link>{!synthetic ? <Link href="/help" style={navStyle}>Docs</Link> : null}<Link href="/login" style={navStyle}>Sign in</Link><Link href="/signup" style={primarySmallStyle}>Create a workspace</Link>
  </header>;
}

function PublicFooter() {
  return <footer style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'flex-start', gap: 28, padding: '26px clamp(16px,3vw,40px) 30px', borderTop: `1px solid ${line}` }}><strong>Unauth</strong><span style={{ flex: 1 }} /><nav style={footerColumn}><b style={footerLabel}>PRODUCT</b><Link href="/pricing">Pricing</Link><Link href="/demo">See it work</Link><Link href="/help">Docs</Link></nav><nav style={footerColumn}><b style={footerLabel}>LEGAL</b><Link href="/legal/privacy">Privacy</Link><Link href="/legal/data-handling">How we handle data</Link><Link href="/legal/dpa">DPA</Link><Link href="/legal/pilot-terms">Pilot terms</Link></nav><p style={{ width: 250, margin: 0, color: faint, font: `400 11px/1.6 ${mono}` }}>Unauth is in controlled pilot. Every figure shown on this site comes from the synthetic Asterlane workspace, not from a customer.</p></footer>;
}

const plans = PUBLIC_PLAN_IDS.map((key) => ({ key, ...PLANS[key] }));

export function PublicOperationsPricing({ requestedPlan }: { requestedPlan?: string }) {
  const selected = parseRequestedPlanId(requestedPlan);
  const requestedPlanUnavailable = Boolean(requestedPlan?.trim()) && selected === null;
  return <div data-screen-label="Pricing" data-visual-world="supplied-package" data-surface-id="pricing" data-operations-surface="pricing" style={{ minHeight: '100vh', background: '#fff', color: ink }}>
    <PublicHeader />
    <main>
      <section style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'flex-end', gap: 28, padding: '52px clamp(16px,3vw,40px) 34px' }}><div style={{ flex: 1, maxWidth: 620 }}><h1 style={{ margin: 0, font: `500 36px/1.15 ${sans}`, letterSpacing: '-.024em' }}>Priced on cases, not on how much loss you have</h1><p style={{ margin: '14px 0 0', color: '#54514c', font: `400 14.5px/1.65 ${sans}` }}>A credit is one case that Unauth opens, enriches and keeps. Reading, deciding, claiming and reconciling that case cost nothing more. Prices are monthly, in GBP, excluding VAT.</p></div><div style={{ display: 'flex', gap: 9, padding: 5, borderRadius: 10, background: '#f4f3f1' }}><span style={{ padding: '7px 13px', borderRadius: 8, background: '#fff', boxShadow: '0 1px 2px rgba(28,27,25,.06)', fontSize: 12.5 }}>Monthly</span><span style={{ padding: '7px 13px', color: faint, fontSize: 12.5 }}>Yearly · two months free</span></div></section>
      {requestedPlanUnavailable ? <section data-state-id="pricing-plan-unavailable" role="status" style={{ margin: '0 clamp(16px,3vw,40px) 18px', padding: '11px 14px', borderRadius: 10, background: '#fdf0e6', color: '#b0431a', fontSize: 12 }}><strong>Plan unavailable. </strong>The requested plan is not in the current catalogue. No plan selection, subscription change, redirect, or saved intent occurred.</section> : null}
      <section style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,240px),1fr))', gap: 14, alignItems: 'start', padding: '0 clamp(16px,3vw,40px) 42px' }}>{plans.map((plan) => {
        const featured = Boolean(plan.featured);
        const price = plan.priceGbp === 'custom' ? 'Talk to us' : `£${formatNumber(plan.priceGbp)}`;
        return <article key={plan.key} aria-current={selected === plan.key ? 'true' : undefined} style={{ display: 'flex', flexDirection: 'column', gap: 15, minHeight: 370, padding: '22px 22px 20px', borderRadius: 14, background: featured ? ink : '#fff', color: featured ? '#fff' : ink, boxShadow: featured ? '0 8px 24px rgba(28,22,14,.18)' : '0 1px 2px rgba(28,27,25,.06),0 0 0 1px rgba(28,27,25,.07)' }}><div><div style={{ display: 'flex', alignItems: 'center', gap: 9 }}><strong style={{ fontSize: 15 }}>{plan.name}</strong>{featured ? <span style={{ marginLeft: 'auto', color: '#f3c18f', fontSize: 9.5 }}>MOST CHOSEN</span> : null}</div><div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginTop: 12 }}><strong style={{ font: `400 27px/1 ${mono}` }}>{price}</strong>{plan.priceGbp !== 'custom' ? <span style={{ color: featured ? '#8f8a83' : faint, font: `400 11.5px/1 ${mono}` }}>a month</span> : null}</div><p style={{ minHeight: 38, margin: '10px 0 0', color: featured ? '#c7c2bb' : muted, fontSize: 12, lineHeight: 1.55 }}>{plan.description}</p></div><ul style={{ display: 'grid', gap: 8, margin: 0, padding: 0, listStyle: 'none' }}>{plan.publicFeatures.slice(0, 6).map((feature) => <li key={feature} style={{ fontSize: 11.5, lineHeight: 1.5 }}>✓ {feature}</li>)}</ul><Link href={`/signup?plan=${plan.key}`} style={{ ...primarySmallStyle, marginTop: 'auto', background: featured ? '#fff' : 'transparent', boxShadow: featured ? 'none' : 'inset 0 0 0 1px rgba(28,27,25,.13)', color: ink }}>{plan.ctaLabel}</Link></article>;
      })}</section>
      <section style={{ padding: '34px clamp(16px,3vw,40px) 44px', borderTop: `1px solid ${line}`, background: '#ffffff' }}><h2 style={{ margin: 0, font: `500 24px/1.25 ${sans}` }}>The price is bounded. The truth is not compressed.</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,220px),1fr))', gap: 28, marginTop: 22 }}><Fact title="No charge for reading a case">Filtering, deciding, reviewing, claiming and reconciling do not silently create another billable event.</Fact><Fact title="Unknown remains unavailable">A missing provider fact never becomes zero to make a plan comparison look cleaner.</Fact><Fact title="You can leave">Export first. Disconnecting retains the history already imported into the workspace.</Fact></div></section>
    </main><PublicFooter />
  </div>;
}

const DEMO_STEPS: Array<{ id: DemoCaseStep; label: string; note: string }> = [
  { id: 'incoming', label: 'Context', note: 'the order, the customer, the complaint' }, { id: 'evidence', label: 'Source facts', note: 'what each system actually reported' }, { id: 'recommendation', label: 'Recommendation', note: 'and the gate it could not close' }, { id: 'decision', label: 'Your decision', note: 'the part Unauth will not make' }, { id: 'recovery', label: 'Recovery', note: 'who pays, by when, and what arrives' },
];
const DEMO_COPY: Record<DemoCaseStep, { title: string; lead: string; facts: Array<[string,string]>; boundary: string }> = {
  incoming: { title: 'A real complaint becomes one bounded case.', lead: 'A £248.00 parcel, a delivered scan, and a customer who says it never arrived.', facts: [['Order','#AS-88301 · £248.00'],['Customer','Maya Cheng · 14 orders'],['Complaint','Nothing arrived'],['Decision','— Not recorded']], boundary: 'Exposure is not liability, and an opened case is not a decision.' },
  evidence: { title: 'Every source says what it knows — and what it does not.', lead: 'The order, warehouse handoff, delivery scan and support statement remain separate facts.', facts: [['Shopify','Paid 21 Aug'],['ShipBob','Manifested 22 Aug'],['UPS','Delivered 24 Aug 14:02'],['Photograph','— Not on this contract']], boundary: 'A photograph that never existed is not a failed fetch and is not evidence against the customer.' },
  recommendation: { title: 'Unauth recommends denying this refund. Here is exactly why, and why it stops there.', lead: 'Eight of nine evidence gates are met. The ninth is the one that decides it.', facts: [['Gates met','8 of 9'],['Confidence','0.71'],['Recommendation','Deny'],['Merchant decision','— Required']], boundary: 'A recommendation is advisory. It cannot refund, deny, notify, or stand in for a named person.' },
  decision: { title: 'Your decision is recorded against your name.', lead: 'The recommendation stays visible, but the merchant outcome is its own append-only record.', facts: [['Outcome','Refund £248.00'],['Actor','Rosa Carrick'],['Rationale','Customer testimony accepted'],['Provider action','Prepared, not sent']], boundary: 'Unauth records the decision. Shopify still moves the money after an authorised handoff.' },
  recovery: { title: 'Recovery follows the money until it is received and reconciled.', lead: 'Claimed, approved, received, matched and reconciled remain different states.', facts: [['Sought','£248.00'],['Approved','— Unavailable'],['Received','£0.00'],['Deadline','13 days left']], boundary: 'Nothing sought or approved is counted as recovered cash before a real received credit is matched.' },
};

export function PublicOperationsProductDemo({ initialStep = 'incoming' }: { initialStep?: DemoCaseStep }) {
  const [step, setStep] = useState<DemoCaseStep>(initialStep);
  const index = useMemo(() => Math.max(0, DEMO_STEPS.findIndex((item) => item.id === step)), [step]);
  const copy = DEMO_COPY[step];
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get('step') !== step) { params.set('step', step); replaceHistoryUrlIfChanged(`/demo?${params.toString()}`); } }, [step]);
  return <div data-screen-label="Demo" data-visual-world="supplied-package" data-surface-id="interactive-product-demo" data-operations-surface="product-demo" data-demo-step={step} style={{ minHeight: '100vh', background: '#fff', color: ink }}>
    <PublicHeader synthetic />
    <nav aria-label="Demo steps" style={{ minHeight: 58, display: 'grid', gridTemplateColumns: 'repeat(5,minmax(150px,1fr))', alignItems: 'center', padding: '0 clamp(16px,3vw,40px)', overflowX: 'auto', borderBottom: `1px solid ${line}` }}>{DEMO_STEPS.map((item, itemIndex) => <button key={item.id} type="button" aria-current={step === item.id ? 'step' : undefined} onClick={() => setStep(item.id)} style={{ display: 'flex', alignItems: 'center', gap: 10, minWidth: 0, padding: 0, border: 0, background: 'transparent', color: itemIndex <= index ? ink : faint, textAlign: 'left', cursor: 'pointer' }}><span style={{ width: 20, height: 20, display: 'grid', placeItems: 'center', flex: '0 0 20px', borderRadius: '50%', background: itemIndex < index ? ink : '#fff', boxShadow: itemIndex === index ? 'inset 0 0 0 2px #ff7a30' : 'inset 0 0 0 1.5px #ddd8d1', color: itemIndex < index ? '#fff' : faint, font: `400 10px/1 ${mono}` }}>{itemIndex < index ? '✓' : itemIndex + 1}</span><span><strong style={{ display: 'block', fontSize: 12.5, fontWeight: itemIndex === index ? 500 : 400 }}>{item.label}</strong><small style={{ display: 'block', marginTop: 2, color: faint, fontSize: 10.5 }}>{item.note}</small></span></button>)}</nav>
    <main style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(min(100%,330px),1fr))', gap: 20, padding: '26px clamp(16px,3vw,40px) 30px' }}><section><h1 style={{ maxWidth: 760, margin: 0, font: `500 24px/1.3 ${sans}`, letterSpacing: '-.016em' }}>{copy.title}</h1><p style={{ maxWidth: 680, margin: '10px 0 0', color: muted, font: `400 13.5px/1.65 ${sans}` }}>{copy.lead}</p><div style={{ marginTop: 16, padding: '16px 18px', borderRadius: 13, boxShadow: '0 1px 2px rgba(28,27,25,.06),0 0 0 1px rgba(28,27,25,.06)' }}><h2 style={{ margin: '0 0 12px', color: muted, font: `600 10.5px/1 ${sans}`, letterSpacing: '.09em' }}>{step === 'recommendation' ? 'THE NINE GATES' : 'THE RECORDED THREAD'}</h2>{copy.facts.map(([label,value]) => <div key={label} style={{ display: 'grid', gridTemplateColumns: '160px 1fr', gap: 16, padding: '10px 0', borderTop: '1px solid #f4f2ef', fontSize: 12 }}><span style={{ color: muted }}>{label}</span><strong style={{ fontFamily: mono }}>{value}</strong></div>)}</div><div style={{ marginTop: 14, padding: '16px 18px', borderRadius: 13, background: ink, color: '#fff' }}><strong>The authority boundary</strong><p style={{ margin: '5px 0 0', color: '#b8b2aa', fontSize: 12, lineHeight: 1.6 }}>{copy.boundary}</p></div></section><aside style={{ display: 'flex', flexDirection: 'column', gap: 12, padding: '16px 17px', borderRadius: 14, background: '#f4f3f1' }}><h2 style={{ margin: 0, color: muted, font: `600 10.5px/1 ${sans}`, letterSpacing: '.09em' }}>WHERE EACH FACT CAME FROM</h2>{[['Shopify','Order #AS-88301, £248.00, paid 21 Aug'],['ShipBob','Manifested 22 Aug, 1 parcel, 0.8 kg'],['UPS','Delivered 24 Aug 14:02, safe place'],['Gorgias','“I was home all day, nothing arrived”']].map(([source,fact]) => <div key={source} style={{ padding: '11px 12px', borderRadius: 10, background: '#fff', boxShadow: '0 1px 2px rgba(28,27,25,.05)' }}><small style={{ color: faint, fontFamily: mono }}>{source}</small><p style={{ margin: '3px 0 0', fontSize: 11.5, lineHeight: 1.5 }}>{fact}</p></div>)}<span style={{ flex: 1 }} /><p style={{ margin: 0, paddingTop: 12, borderTop: '1px solid #e4e3e0', color: muted, fontSize: 11.5, lineHeight: 1.6 }}>Asterlane is synthetic. The orders, customers, and carriers are invented; the authority boundaries are the same product code paths.</p><div style={{ display: 'flex', gap: 8 }}><button type="button" disabled={index === 0} onClick={() => setStep(DEMO_STEPS[Math.max(0,index - 1)].id)} style={secondaryButtonStyle}>Back</button><button type="button" onClick={() => setStep(DEMO_STEPS[(index + 1) % DEMO_STEPS.length].id)} style={{ ...primarySmallStyle, flex: 1, border: 0 }}>{index === 4 ? 'Back to context' : `Next: ${DEMO_STEPS[index + 1].label.toLowerCase()}`}</button></div></aside></main>
  </div>;
}

function Fact({ title, children }: { title: string; children: ReactNode }) { return <article><h3 style={{ margin: 0, fontSize: 14 }}>{title}</h3><p style={{ margin: '7px 0 0', color: muted, fontSize: 12.5, lineHeight: 1.65 }}>{children}</p></article>; }
const navStyle = { color: '#40454a', font: `400 13px/1 ${sans}`, textDecoration: 'none' } as const;
const primarySmallStyle = { padding: '8px 13px', borderRadius: 9, background: ink, color: '#fff', font: `500 12.5px/1 ${sans}`, textDecoration: 'none', textAlign: 'center' } as const;
const secondaryButtonStyle = { padding: '8px 13px', border: 0, borderRadius: 9, boxShadow: 'inset 0 0 0 1px rgba(28,27,25,.13)', background: '#fff', color: '#40454a', fontSize: 12.5 } as const;
const footerColumn = { display: 'grid', gap: 9, width: 190 } as const;
const footerLabel = { color: faint, font: `600 10px/1 ${sans}`, letterSpacing: '.09em' } as const;
