import type { ReactNode } from 'react';

interface EmptyStateBaseProps { icon?: ReactNode; title: string; footer?: ReactNode; className?: string; }
type EmptyStateProps = EmptyStateBaseProps & ({ variant?: 'default' | 'compact'; description: string; action: Exclude<ReactNode, null | undefined | boolean>; children?: never } | { variant: 'hero'; description?: string; action?: ReactNode; children: ReactNode });

export function EmptyState({ variant = 'default', icon, title, description, action, footer, className: _className, children }: EmptyStateProps) {
  if (variant === 'hero') return <div style={{ width: '100%' }}>{children}</div>;
  if (variant === 'compact') return <div style={{ padding: '32px 16px' }}><h2 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: 8, color: '#1c1f23', font: "500 13px/1.5 'Inter',sans-serif" }}>{icon ? <span aria-hidden="true" style={{ flex: 'none', display: 'inline-flex', padding: '4px 8px', borderRadius: 6, background: '#f4f3f1', color: '#40454a', fontSize: 10 }}>{icon}</span> : <span aria-hidden="true" style={{ width: 8, height: 8, flex: 'none', borderRadius: '50%', background: '#a7abad' }}/>} {title}</h2>{description ? <p style={{ margin: '4px 0 0', color: '#64686d', font: "400 11px/1.45 'Inter',sans-serif" }}>{description}</p> : null}{action ? <div style={{ marginTop: 12 }}>{action}</div> : null}{footer ? <div style={{ marginTop: 12 }}>{footer}</div> : null}</div>;
  return <div role="status" data-kind="empty" style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '32px 24px', border: '1px solid #e4e3e0', borderRadius: 12, background: '#fff', color: '#40454a', textAlign: 'center' }}>{icon ? <span aria-hidden="true" style={{ width: 40, height: 40, marginBottom: 12, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', border: '1px solid #e4e3e0', borderRadius: 8, background: '#fff', color: '#64686d' }}>{icon}</span> : null}<h3 style={{ margin: 0, color: '#1c1f23', font: "500 14px/1.4 'Inter',sans-serif" }}>{title}</h3>{description ? <p style={{ maxWidth: 520, margin: '5px 0 0', color: '#64686d', font: "400 11px/1.45 'Inter',sans-serif" }}>{description}</p> : null}{action ? <div style={{ marginTop: 20 }}>{action}</div> : null}{footer ? <div style={{ width: '100%', marginTop: 20 }}>{footer}</div> : null}</div>;
}
