'use client';
import { cloneElement, forwardRef, useId, type InputHTMLAttributes, type ReactElement, type ReactNode, type TextareaHTMLAttributes } from 'react';
import { cn } from '@/lib/utils';
type Control = { id?: string; 'aria-describedby'?: string; 'aria-invalid'?: boolean; className?: string };
export function FormField({ label, hint, error, optional = false, success, children, className }: { label: ReactNode; hint?: ReactNode; error?: ReactNode; optional?: boolean; success?: ReactNode; children: ReactElement<Control>; className?: string }) { const seed = useId().replaceAll(':', ''); const id = children.props.id ?? `field-${seed}`; const hintId = hint ? `${id}-hint` : undefined; const errorId = error ? `${id}-error` : undefined; const successId = success ? `${id}-success` : undefined; const describedBy = [children.props['aria-describedby'], hintId, errorId, successId].filter(Boolean).join(' '); return <div className={cn('ua-form-field', className)} data-invalid={error ? 'true' : undefined}><label className="ua-form-field__label" htmlFor={id}><span>{label}</span>{optional ? <span className="ua-form-field__optional">Optional</span> : null}</label>{cloneElement(children, { id, 'aria-describedby': describedBy || undefined, 'aria-invalid': error ? true : undefined, className: cn('ua-form-control', children.props.className) })}{hint ? <p id={hintId} className="ua-form-field__hint">{hint}</p> : null}{error ? <p id={errorId} className="ua-form-field__error" role="alert">{error}</p> : null}{success ? <p id={successId} className="ua-form-field__success" role="status">{success}</p> : null}</div>; }
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(function Textarea({ className, ...props }, ref) { return <textarea ref={ref} className={cn('ua-form-control ua-textarea', className)} {...props} />; });
export const Checkbox = forwardRef<HTMLInputElement, Omit<InputHTMLAttributes<HTMLInputElement>, 'type'>>(function Checkbox({ className, ...props }, ref) { return <input ref={ref} type="checkbox" className={cn('ua-checkbox', className)} {...props} />; });
export function Switch({ label, description, className, ...props }: Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> & { label: ReactNode; description?: ReactNode }) { return <label className={cn('ua-switch-row', className)}><span className="ua-switch-row__copy"><strong>{label}</strong>{description ? <span>{description}</span> : null}</span><span className="ua-switch"><input type="checkbox" role="switch" {...props} /><span className="ua-switch__track" aria-hidden="true"><span className="ua-switch__thumb" /></span></span></label>; }
export function RadioGroup({ legend, children, className }: { legend: ReactNode; children: ReactNode; className?: string }) { return <fieldset className={cn('ua-radio-group', className)}><legend>{legend}</legend><div className="ua-radio-group__options">{children}</div></fieldset>; }
