/**
 * Executable implementation map for the Unauth frontend.
 *
 * Current implementation authority: design-system.md
 * Historical route-contract lookup:
 * docs/unauth-ui/frontend-design-system-and-surface-build-specification.md
 *
 * This file records ownership and phase boundaries. It is not a navigation
 * registry and must not be used to create duplicate links for compatibility
 * aliases or redirect-only routes.
 */

export type SurfaceMaturity =
  | 'standardize'
  | 'refine'
  | 'build'
  | 'adapter'
  | 'unavailable';

export type VisualDisposition = 'replace' | 'frozen' | 'adapter';

export type ImplementationPhase =
  | 'p01'
  | 'p02'
  | 'p03'
  | 'p04'
  | 'p05'
  | 'p06'
  | 'p07'
  | 'p08';

export type SurfaceManifestEntry = {
  id: string;
  pathPattern: string;
  pageModule: string;
  shell: string;
  archetype: string;
  maturity: SurfaceMaturity;
  phase: ImplementationPhase;
  primaryComponents: readonly string[];
  dataDependencies: readonly string[];
  ownedStates: readonly string[];
  ownedOverlays: readonly string[];
  queryState: readonly string[];
  legacyAliases: readonly string[];
  responsiveFamily: string;
};

export type ScenarioContract = {
  id: string;
  owner: string;
  pageModule: string | null;
  kind: 'route' | 'state' | 'overlay' | 'loading' | 'not-found' | 'error' | 'adapter';
  disposition: VisualDisposition;
  viewportFamily: string;
  activationRecipe: string;
  readiness: 'visual-ready' | 'redirect-complete';
};

/** P00 authority order recorded from design-system.md section 0. */
export const specificationAuthorities = {
  productTruth: 'PRODUCT.md',
  executableSurfaceMap: 'lib/surfaces/manifest.ts',
  canonicalNavigation: 'lib/navigation/appRoutes.ts',
  legacyRedirects: 'lib/navigation/aliases.js',
  redirectConsumer: 'next.config.js',
  visualSystem: 'DESIGN.md',
  implementationGuide: 'design-system.md',
  historicalRouteContracts: 'docs/unauth-ui/frontend-design-system-and-surface-build-specification.md',
  humanReadableInventory: 'docs/page-inventory.md',
} as const;

/**
 * The checkout has no separate aliases.ts file. appRoutes.ts consumes the
 * CommonJS table directly, which also lets next.config.js share the same
 * redirect authority without introducing a second alias database.
 */
export const navigationAuthorities = {
  canonicalNavigation: 'lib/navigation/appRoutes.ts',
  legacyRedirects: 'lib/navigation/aliases.js',
  nextRedirectConsumer: 'next.config.js',
} as const;

/**
 * P00 authority boundary. Component names throughout this manifest describe
 * target contracts only; they never approve a similarly named incumbent
 * implementation. Presentation is replaced transitively as its owning phase
 * reaches it, while the non-visual product contracts below remain binding.
 */
export const implementationAuthority = {
  presentationDisposition: 'replace-completely',
  incumbentPresentationFitness: 'not-fit-for-purpose',
  componentNamesAre: 'target-contracts-not-implementation-approval',
  prohibitedStrategies: [
    'reuse-incumbent-component',
    'wrap-incumbent-component',
    'skin-or-theme-incumbent-component',
    'parallel-legacy-component-family',
    'legacy-style-or-token-fallback',
  ],
  protectedTruth: [
    'canonical-routes-and-aliases',
    'query-and-navigation-state',
    'backend-and-data-contracts',
    'authentication-authorization-and-tenancy',
    'integer-minor-unit-financial-semantics',
    'mutations-events-and-audit-consequences',
  ],
} as const;

/**
 * One entry per concrete page.tsx module. Hybrid archetypes preserve the
 * explicit contracts in section 19 instead of flattening them to a generic
 * route type.
 */
export const surfaceManifest = [
  {
    id: 'marketing-landing',
    pathPattern: '/landing',
    pageModule: 'app/(public)/landing/page.tsx',
    shell: 'PublicShell',
    archetype: 'P1',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['NeutralLanding'],
    dataDependencies: ['public-product-content', 'provider-catalogue'],
    ownedStates: [],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'pricing',
    pathPattern: '/pricing',
    pageModule: 'app/(public)/pricing/page.tsx',
    shell: 'PublicShell',
    archetype: 'P1',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6Pricing', 'PublicHeader'],
    dataDependencies: ['billing-plan-catalogue', 'usage-credit-configuration'],
    ownedStates: ['pricing-plan-unavailable'],
    ownedOverlays: [],
    queryState: ['plan'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'interactive-product-demo',
    pathPattern: '/demo',
    pageModule: 'app/(public)/demo/page.tsx',
    shell: 'PublicShell',
    archetype: 'P1/P8',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6ProductDemo'],
    dataDependencies: ['synthetic-demo-case'],
    ownedStates: ['demo-loading', 'demo-error'],
    ownedOverlays: [],
    queryState: ['step'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'create-account',
    pathPattern: '/signup',
    pageModule: 'app/(public)/signup/page.tsx',
    shell: 'PublicShell',
    archetype: 'P2',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['SignupForm', 'AuthShell', 'FormField', 'Input', 'Button'],
    dataDependencies: ['supabase-auth-signup', 'subscription-intents'],
    ownedStates: ['signup-submitting', 'signup-error'],
    ownedOverlays: [],
    queryState: ['next', 'plan'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'sign-in',
    pathPattern: '/login',
    pageModule: 'app/(auth)/login/page.tsx',
    shell: 'AuthShell',
    archetype: 'P2',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['LoginForm', 'FormField', 'Input', 'Button'],
    dataDependencies: ['supabase-auth-session'],
    ownedStates: ['login-submitting', 'login-error'],
    ownedOverlays: [],
    queryState: ['next', 'plan'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'request-password-reset',
    pathPattern: '/reset',
    pageModule: 'app/(auth)/reset/page.tsx',
    shell: 'AuthShell',
    archetype: 'P2',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['ResetForm', 'FormField', 'Input', 'Button'],
    dataDependencies: ['supabase-password-recovery'],
    ownedStates: ['password-reset-sent-state', 'password-reset-error'],
    ownedOverlays: [],
    queryState: ['next'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'set-new-password',
    pathPattern: '/reset/update',
    pageModule: 'app/(auth)/reset/update/page.tsx',
    shell: 'AuthShell',
    archetype: 'P2',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['UpdatePasswordForm', 'FormField', 'Input', 'Button'],
    dataDependencies: ['supabase-password-recovery-session'],
    ownedStates: ['reset-update-invalid-session', 'reset-update-success', 'reset-update-error'],
    ownedOverlays: [],
    queryState: ['next'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'workspace-onboarding-store-profile',
    pathPattern: '/onboarding',
    pageModule: 'app/onboarding/page.tsx',
    shell: 'OnboardingShell',
    archetype: 'P3',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['OnboardingClient'],
    dataDependencies: ['workspace-profile', 'commerce-connections', 'helpdesk-connections'],
    ownedStates: [
      'workspace-onboarding-shopify-connection',
      'workspace-onboarding-helpdesk-connection',
      'workspace-onboarding-setup-verified',
      'onboarding-loading',
      'onboarding-error',
    ],
    ownedOverlays: [],
    queryState: ['step', 'next'],
    legacyAliases: [],
    responsiveFamily: 'public-auth-onboarding',
  },
  {
    id: 'overview-dashboard',
    pathPattern: '/overview',
    pageModule: 'app/(app)/overview/page.tsx',
    shell: 'AppShell',
    archetype: 'P4',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['DashboardOverview', 'ChartFrame', 'ProductValue', 'FreshnessIndicator'],
    dataDependencies: ['dashboard-financial-metrics', 'attention-queue', 'source-health'],
    ownedStates: ['overview-unavailable-and-no-work-states', 'overview-dashboard-loading', 'overview-error'],
    ownedOverlays: ['overview-data-trust-details-modal'],
    queryState: ['range', 'compare', 'currency', 'metric'],
    legacyAliases: ['/dashboard', '/store/:path*', '/network-metrics/:path*', '/eval/:path*'],
    responsiveFamily: 'overview-report',
  },
  {
    id: 'work-queue',
    pathPattern: '/work',
    pageModule: 'app/(app)/work/page.tsx',
    shell: 'AppShell',
    archetype: 'P5/P6',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: [
      'WorkQueueOperations',
      'Inspector',
      'Pagination',
      'ExceptionResolutionDrawer',
    ],
    dataDependencies: ['work-tasks', 'integration-exceptions', 'saved-work-views'],
    ownedStates: [
      'saved-work-views',
      'work-empty-search-states',
      'operational-list-board-loading-skeleton',
      'work-error',
    ],
    ownedOverlays: ['integration-exception-resolution-drawer'],
    queryState: ['view', 'search', 'priority', 'state', 'assignee', 'sort', 'page', 'savedView', 'selected'],
    legacyAliases: ['/exceptions'],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'cases-registry',
    pathPattern: '/cases',
    pageModule: 'app/(app)/cases/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['ClaimsPage'],
    dataDependencies: ['cases', 'case-financial-summary', 'case-ownership'],
    ownedStates: ['cases-empty-filter-states', 'cases-registry-loading', 'cases-error'],
    ownedOverlays: ['case-context-drawer'],
    queryState: ['search', 'queue', 'status', 'owner', 'sort', 'selected'],
    legacyAliases: [
      '/inbox',
      '/claims',
      '/claims/:path*',
      '/catches/:path*',
      '/chargebacks/:path*',
      '/evidence',
      '/evidence-packages',
    ],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'customers-registry',
    pathPattern: '/customers',
    pageModule: 'app/(app)/customers/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['CustomersOverviewPageView', 'CustomersTableClient', 'CustomerPreviewDrawer'],
    dataDependencies: ['customers', 'customer-case-summary', 'customer-financial-summary'],
    ownedStates: ['customers-empty-filter-states', 'customers-registry-loading', 'customers-error'],
    ownedOverlays: ['customer-preview-drawer'],
    queryState: ['search', 'status', 'risk', 'sort', 'selected'],
    legacyAliases: [
      '/lookup/:path*',
      '/global/:path*',
      '/graph/:path*',
      '/clusters/:path*',
      '/watchlist/:path*',
    ],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'loss-ledger',
    pathPattern: '/financials/losses',
    pageModule: 'app/(app)/financials/losses/page.tsx',
    shell: 'AppShell',
    archetype: 'P9/P5',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['LossesPage', 'LossLedgerOperations', 'PageFrame', 'ExportMenu'],
    dataDependencies: ['loss-ledger', 'loss-trend', 'financial-scope'],
    ownedStates: ['loss-chart-ledger-unavailable-states', 'operational-list-board-loading-skeleton', 'losses-error'],
    ownedOverlays: [],
    queryState: ['range', 'currency', 'source', 'status', 'search', 'sort', 'page'],
    legacyAliases: ['/losses', '/losses/:path*'],
    responsiveFamily: 'overview-report',
  },
  {
    id: 'recovery-board',
    pathPattern: '/financials/recovery',
    pageModule: 'app/(app)/financials/recovery/page.tsx',
    shell: 'AppShell',
    archetype: 'P6',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['RecoveryPage', 'RecoveryBoardOperations', 'PageFrame', 'ExportMenu'],
    dataDependencies: ['recovery-cases', 'recovery-stages', 'recovery-tasks'],
    ownedStates: ['recovery-board-empty-state', 'operational-list-board-loading-skeleton', 'recovery-board-error'],
    ownedOverlays: ['confirm-recovery-action-modal', 'case-context-drawer'],
    queryState: ['stage', 'owner', 'source', 'search', 'selected'],
    legacyAliases: ['/recoveries', '/recoveries/:path*'],
    responsiveFamily: 'work-board',
  },
  {
    id: 'reconciliation-exception-workspace',
    pathPattern: '/financials/reconciliation',
    pageModule: 'app/(app)/financials/reconciliation/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8',
    maturity: 'refine',
    phase: 'p03',
    primaryComponents: ['ExceptionQueue', 'ReconciliationOperations', 'PageFrame', 'ExportMenu'],
    dataDependencies: ['reconciliation-exceptions', 'source-records', 'ledger-records'],
    ownedStates: ['reconciliation-loading-empty-states', 'reconciliation-error'],
    ownedOverlays: ['reconciliation-resolution-drawer'],
    queryState: ['status', 'source', 'search', 'selected'],
    legacyAliases: [],
    responsiveFamily: 'reconciliation-workbench',
  },
  {
    id: 'financial-reports',
    pathPattern: '/financials/reports',
    pageModule: 'app/(app)/financials/reports/page.tsx',
    shell: 'AppShell',
    archetype: 'P9',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['ReportsPage', 'ReportCommandIndex', 'FinancialEquation', 'ChartFrame'],
    dataDependencies: ['financial-reports', 'financial-scope', 'report-definitions'],
    ownedStates: ['reports-and-records-loading', 'reports-unavailable-zero', 'reports-error'],
    ownedOverlays: [],
    queryState: ['range', 'compare', 'currency', 'report'],
    legacyAliases: [
      '/reports',
      '/reports/:path*',
      '/audit/:path*',
      '/report/:path*',
      '/audits/:path*',
      '/audit-history',
      '/history/:path*',
      '/saved/:path*',
    ],
    responsiveFamily: 'overview-report',
  },
  {
    id: 'report-supporting-records',
    pathPattern: '/financials/reports/records',
    pageModule: 'app/(app)/financials/reports/records/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['PageFrame', 'RegistrySurface', 'DataTableServer', 'RegistryToolbar', 'Pagination'],
    dataDependencies: ['report-records', 'financial-scope'],
    ownedStates: ['reports-and-records-loading', 'report-records-empty', 'report-records-error'],
    ownedOverlays: [],
    queryState: ['reportId', 'range', 'currency', 'search', 'sort', 'page', 'pageSize'],
    legacyAliases: [],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'payout-rules-registry',
    pathPattern: '/controls/rules',
    pageModule: 'app/(app)/controls/rules/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['RulesPage', 'RulesIndexClient', 'DataTable', 'RuleBuilderDrawer'],
    dataDependencies: ['rules', 'rule-versions', 'rule-rollout-state'],
    ownedStates: ['rules-empty-state', 'operational-list-board-loading-skeleton', 'rules-error'],
    ownedOverlays: ['rule-builder-drawer'],
    queryState: ['search', 'state', 'type', 'sort', 'selected'],
    legacyAliases: ['/rules', '/rules/:path*', '/partners'],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'recovery-rulebook',
    pathPattern: '/controls/rules/recovery',
    pageModule: 'app/(app)/controls/rules/recovery/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8/P10',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['RecoveryRulebookClient', 'DataTable', 'StatusBadge', 'Modal'],
    dataDependencies: ['partners', 'partner-recovery-rules'],
    ownedStates: ['recovery-rulebook-empty', 'recovery-rulebook-error'],
    ownedOverlays: ['partner-and-recovery-rule-modals'],
    queryState: ['partner', 'state', 'selected'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'flows-registry',
    pathPattern: '/controls/flows',
    pageModule: 'app/(app)/controls/flows/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['FlowsPage', 'FlowsIndexClient', 'DataTable'],
    dataDependencies: ['workflows', 'workflow-versions'],
    ownedStates: ['flows-empty-state', 'operational-list-board-loading-skeleton', 'flows-error'],
    ownedOverlays: ['new-flow-draft-modal'],
    queryState: ['search', 'state', 'sort'],
    legacyAliases: ['/flows', '/flows/:path*'],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'flow-runs-registry',
    pathPattern: '/controls/flows/runs',
    pageModule: 'app/(app)/controls/flows/runs/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['FlowRunsPage', 'DataTableServer', 'StatusWithReason', 'Pagination'],
    dataDependencies: ['workflow-runs', 'workflow-definitions'],
    ownedStates: ['operational-list-board-loading-skeleton', 'flow-runs-empty', 'flow-runs-error'],
    ownedOverlays: [],
    queryState: ['workflow', 'state', 'range', 'search', 'page'],
    legacyAliases: [],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'connected-sources',
    pathPattern: '/sources/connected',
    pageModule: 'app/(app)/sources/connected/page.tsx',
    shell: 'AppShell',
    archetype: 'P5/P4',
    maturity: 'standardize',
    phase: 'p05',
    primaryComponents: ['SourceConnectionsPage', 'SourcesOperations', 'ProviderLogo', 'PageFrame'],
    dataDependencies: ['source-connections', 'source-health', 'source-coverage'],
    ownedStates: ['operational-list-board-loading-skeleton', 'connected-sources-empty', 'connected-sources-error'],
    ownedOverlays: ['connection-and-disconnection-modals'],
    queryState: ['status', 'category', 'q'],
    legacyAliases: ['/integrations', '/settings/integrations'],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'source-catalogue',
    pathPattern: '/sources/browse',
    pageModule: 'app/(app)/sources/browse/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p05',
    primaryComponents: ['SourceConnectionsPage', 'SourcesOperations', 'ProviderLogo', 'PageFrame'],
    dataDependencies: ['provider-catalogue', 'source-connections'],
    ownedStates: ['source-catalogue-no-results', 'source-catalogue-error'],
    ownedOverlays: [],
    queryState: ['category', 'q'],
    legacyAliases: [],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'csv-imports',
    pathPattern: '/sources/imports',
    pageModule: 'app/(app)/sources/imports/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8',
    maturity: 'standardize',
    phase: 'p05',
    primaryComponents: ['ImportsPage', 'CanonicalCsvImportClient', 'WorkbenchPage', 'DataTable'],
    dataDependencies: ['csv-validation', 'csv-import-commit', 'import-job-history'],
    ownedStates: ['import-validation-empty-states', 'imports-error'],
    ownedOverlays: ['replace-import-file-confirmation'],
    queryState: ['step'],
    legacyAliases: ['/new-audit', '/upload/:path*'],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'notifications-inbox',
    pathPattern: '/notifications',
    pageModule: 'app/(app)/notifications/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['NotificationCentre', 'DataTable', 'Tabs', 'StatusBadge'],
    dataDependencies: ['notifications', 'unread-count'],
    ownedStates: ['notifications-empty-states', 'notifications-loading', 'notifications-error'],
    ownedOverlays: [],
    queryState: ['tab', 'page'],
    legacyAliases: [],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'search-route',
    pathPattern: '/search',
    pageModule: 'app/(app)/search/page.tsx',
    shell: 'AppShell',
    archetype: 'P5',
    maturity: 'build',
    phase: 'p07',
    primaryComponents: ['WorkspaceSearch', 'PageFrame'],
    dataDependencies: ['entity-search'],
    ownedStates: ['search-empty', 'search-no-results', 'search-error'],
    ownedOverlays: [],
    queryState: ['q', 'type', 'source', 'page'],
    legacyAliases: [],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'case-review-workbench',
    pathPattern: '/cases/[caseId]',
    pageModule: 'app/(app)/cases/[caseId]/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: [
      'CaseDetailRoute',
      'ClaimReviewPanel',
      'CaseDetailOperations',
      'CaseTruthStrip',
      'CaseInvestigationsCard',
      'CaseFinancialHistoryCard',
      'ActivityTimeline',
    ],
    dataDependencies: ['case-evidence-file', 'investigations', 'recommendations', 'merchant-decisions', 'external-action-ledger', 'external-outcomes', 'responsibility', 'recovery', 'financial-stages', 'comments', 'audit-context'],
    ownedStates: ['operational-detail-loading-skeleton', 'case-not-found', 'case-error'],
    ownedOverlays: [
      'record-or-reverse-merchant-decision-modals',
      'investigation-request-modal',
      'investigation-response-modal',
      'investigation-lifecycle-action-modal',
      'responsibility-assessment-modal',
      'delivery-photo-finding-modal',
    ],
    queryState: ['tab', 'investigationId', 'return'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'customer-profile',
    pathPattern: '/customers/[id]',
    pageModule: 'app/(app)/customers/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['CustomerProfilePageView', 'PageFrame', 'CustomerProfilePageMainColumn', 'CustomerProfileMetrics'],
    dataDependencies: ['customer-profile', 'customer-orders', 'customer-cases', 'customer-notes'],
    ownedStates: ['customer-profile-access-blocked-state', 'operational-detail-loading-skeleton', 'customer-not-found', 'customer-error'],
    ownedOverlays: ['customer-note-editor'],
    queryState: ['tab'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'build-evidence-package',
    pathPattern: '/customers/[id]/evidence/new',
    pageModule: 'app/(app)/customers/[id]/evidence/new/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8/P2',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['EvidenceNewPageContent', 'EvidencePackageForm', 'PageFrame', 'ProductValue'],
    dataDependencies: ['customer-profile', 'customer-orders', 'customer-cases', 'evidence-package'],
    ownedStates: ['evidence-package-no-orders-no-cases-states', 'evidence-package-builder-loading', 'evidence-package-error'],
    ownedOverlays: [],
    queryState: ['orderId', 'caseId'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'order-detail',
    pathPattern: '/orders/[id]',
    pageModule: 'app/(app)/orders/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-order'],
    ownedStates: ['connected-record-not-found', 'commerce-object-loading', 'order-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'refund-detail',
    pathPattern: '/refunds/[id]',
    pageModule: 'app/(app)/refunds/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-refund'],
    ownedStates: ['connected-record-not-found', 'commerce-object-loading', 'refund-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'return-detail',
    pathPattern: '/returns/[id]',
    pageModule: 'app/(app)/returns/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-return'],
    ownedStates: ['connected-record-not-found', 'commerce-object-loading', 'return-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'shipment-detail',
    pathPattern: '/shipments/[id]',
    pageModule: 'app/(app)/shipments/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-shipment'],
    ownedStates: ['connected-record-not-found', 'commerce-object-loading', 'shipment-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'support-ticket-detail',
    pathPattern: '/tickets/[id]',
    pageModule: 'app/(app)/tickets/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-support-ticket'],
    ownedStates: ['connected-record-not-found', 'support-object-loading', 'ticket-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'dispute-detail',
    pathPattern: '/disputes/[id]',
    pageModule: 'app/(app)/disputes/[id]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p02',
    primaryComponents: ['connectedObjectPage', 'ConnectedObjectDetail', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['connected-dispute'],
    ownedStates: ['connected-record-not-found', 'support-object-loading', 'dispute-error'],
    ownedOverlays: [],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'loss-detail',
    pathPattern: '/financials/losses/[lossId]',
    pageModule: 'app/(app)/financials/losses/[lossId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['LossDetailPage', 'LossActions', 'UnavailableValue'],
    dataDependencies: ['loss-record', 'loss-events', 'recovery-summary'],
    ownedStates: ['connected-record-not-found', 'operational-detail-loading-skeleton', 'loss-detail-error'],
    ownedOverlays: ['write-off-outstanding-recovery-modal'],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'recovery-detail',
    pathPattern: '/financials/recovery/[recoveryId]',
    pageModule: 'app/(app)/financials/recovery/[recoveryId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p03',
    primaryComponents: ['RecoveryDetailPage', 'RecoveryDetailOperations', 'RecoveryDetailActions', 'PageFrame'],
    dataDependencies: ['recovery-case', 'recovery-correspondence', 'recovery-credits'],
    ownedStates: ['operational-detail-loading-skeleton', 'recovery-not-found', 'recovery-detail-error'],
    ownedOverlays: ['recovery-detail-action-modal'],
    queryState: ['tab'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'rule-version-workbench',
    pathPattern: '/controls/rules/[ruleId]',
    pageModule: 'app/(app)/controls/rules/[ruleId]/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['RuleDetailPage', 'RuleVersionWorkbench', 'PageFrame', 'SetBreadcrumbLabel'],
    dataDependencies: ['rule', 'rule-versions', 'rule-simulation'],
    ownedStates: ['operational-detail-loading-skeleton', 'rule-not-found', 'rule-detail-error'],
    ownedOverlays: ['rule-simulation-and-publication-modals'],
    queryState: ['version', 'tab'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'flow-version-workbench',
    pathPattern: '/controls/flows/[flowId]',
    pageModule: 'app/(app)/controls/flows/[flowId]/page.tsx',
    shell: 'WorkbenchShell',
    archetype: 'P8',
    maturity: 'standardize',
    phase: 'p04',
    primaryComponents: ['FlowDetailPage', 'FlowVersionWorkbench', 'PageFrame', 'SetBreadcrumbLabel'],
    dataDependencies: ['workflow', 'workflow-versions', 'workflow-tests'],
    ownedStates: ['operational-detail-loading-skeleton', 'flow-not-found', 'flow-detail-error'],
    ownedOverlays: ['flow-edit-test-and-publication-modals'],
    queryState: ['version', 'step', 'tab'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'flow-run-detail',
    pathPattern: '/controls/flows/runs/[runId]',
    pageModule: 'app/(app)/controls/flows/runs/[runId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7/P8',
    maturity: 'refine',
    phase: 'p04',
    primaryComponents: ['FlowRunDetailPage', 'FlowRunTrace', 'DetailPageShell', 'AuditTimeline'],
    dataDependencies: ['workflow-run', 'workflow-run-steps'],
    ownedStates: ['operational-detail-loading-skeleton', 'flow-run-not-found', 'flow-run-error'],
    ownedOverlays: ['flow-run-payload-inspector'],
    queryState: ['step'],
    legacyAliases: [],
    responsiveFamily: 'builder-trace',
  },
  {
    id: 'source-detail',
    pathPattern: '/sources/[sourceId]',
    pageModule: 'app/(app)/sources/[sourceId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7',
    maturity: 'standardize',
    phase: 'p05',
    primaryComponents: ['SourceDetailPage', 'SourceDetailOperations', 'SourceConnectionActionsOperations', 'PageFrame'],
    dataDependencies: ['source-connection', 'source-health', 'source-capabilities'],
    ownedStates: ['operational-list-board-loading-skeleton', 'source-unavailable', 'source-not-found', 'source-error'],
    ownedOverlays: ['connection-and-disconnection-modals'],
    queryState: ['tab'],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
  {
    id: 'provider-specific-connector-setup',
    pathPattern: '/sources/setup/[providerId]',
    pageModule: 'app/(app)/sources/setup/[providerId]/page.tsx',
    shell: 'AppShell',
    archetype: 'P3',
    maturity: 'refine',
    phase: 'p05',
    primaryComponents: ['SourceSetupWizard', 'ConnectorSetupShell', 'ConnectionActions'],
    dataDependencies: ['provider-catalogue', 'provider-connection-state', 'connector-actions'],
    ownedStates: ['generic-seven-step-source-setup', 'settings-form-loading-families', 'connector-setup-error'],
    ownedOverlays: ['connection-and-disconnection-modals', 'connect-shopify-modal'],
    queryState: ['step', 'returnTo'],
    legacyAliases: ['/integrations/:path*', '/settings/integrations/:provider'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'shipbob-channel-selection',
    pathPattern: '/sources/setup/shipbob/select',
    pageModule: 'app/(app)/sources/setup/shipbob/select/page.tsx',
    shell: 'AppShell',
    archetype: 'P2',
    maturity: 'standardize',
    phase: 'p05',
    primaryComponents: ['ShipBobAccountSelectionClient', 'ConnectorSetupShell', 'FormField', 'Button'],
    dataDependencies: ['shipbob-channels', 'shipbob-selection'],
    ownedStates: ['settings-form-loading-families', 'shipbob-selection-empty', 'shipbob-selection-error'],
    ownedOverlays: [],
    queryState: ['returnTo'],
    legacyAliases: ['/integrations/shipbob/select'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'account-and-appearance',
    pathPattern: '/settings/workspace/account',
    pageModule: 'app/(app)/settings/workspace/account/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['AccountSettingsPage', 'HandoffSettingsNav', 'AccountProfileSection', 'AccountPasswordSection'],
    dataDependencies: ['workspace-profile', 'account-credentials'],
    ownedStates: ['settings-form-loading-families', 'account-settings-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: ['/settings', '/settings/account'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'team-management',
    pathPattern: '/settings/workspace/team',
    pageModule: 'app/(app)/settings/workspace/team/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P5/P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['TeamSettingsPage', 'TeamManagementClient', 'TeamMembersTable'],
    dataDependencies: ['team-members', 'team-permissions'],
    ownedStates: ['settings-form-loading-families', 'team-empty', 'team-error'],
    ownedOverlays: ['invite-member-and-transfer-ownership-modals'],
    queryState: ['search', 'role'],
    legacyAliases: ['/settings/team'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'platform-defaults',
    pathPattern: '/settings/product/platform',
    pageModule: 'app/(app)/settings/product/platform/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['PlatformSettingsPage', 'PlatformSettingsClient', 'JoinedSection', 'Select'],
    dataDependencies: ['platform-settings'],
    ownedStates: ['settings-form-loading-families', 'platform-settings-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: ['/settings/platform'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'notification-preferences',
    pathPattern: '/settings/product/notifications',
    pageModule: 'app/(app)/settings/product/notifications/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['NotificationsSettingsPage', 'SettingsPageShell', 'StatusWithReason'],
    dataDependencies: ['notification-preferences', 'notification-capabilities'],
    ownedStates: ['settings-form-loading-families', 'notification-email-unavailable', 'notification-settings-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: ['/settings/notifications'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'developer-api-access',
    pathPattern: '/settings/developers/api-access',
    pageModule: 'app/(app)/settings/developers/api-access/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10/P5',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['ApiAccessSettingsPage', 'ApiIntegrationsClient', 'SettingsPageShell', 'ApiIntegrationsAdvancedSection'],
    dataDependencies: ['api-keys'],
    ownedStates: ['settings-form-loading-families', 'api-keys-empty', 'api-access-error'],
    ownedOverlays: ['create-reveal-and-revoke-api-key-modals'],
    queryState: [],
    legacyAliases: ['/settings/api-integrations'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'audit-trail',
    pathPattern: '/settings/governance/audit-trail',
    pageModule: 'app/(app)/settings/governance/audit-trail/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P5',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['AuditTrailSettingsPage', 'AuditTrailClient', 'DataTableServer', 'AuditTimeline'],
    dataDependencies: ['audit-events'],
    ownedStates: ['settings-form-loading-families', 'audit-trail-empty', 'audit-trail-error'],
    ownedOverlays: ['audit-event-detail-drawer'],
    queryState: ['actor', 'action', 'range', 'search', 'page'],
    legacyAliases: ['/settings/audit-trail'],
    responsiveFamily: 'registry-table',
  },
  {
    id: 'data-privacy',
    pathPattern: '/settings/legal/data-privacy',
    pageModule: 'app/(app)/settings/legal/data-privacy/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['DataPrivacySettingsPage', 'SubjectErasureClient', 'BulkDeleteClient'],
    dataDependencies: ['privacy-policy', 'erasure-requests'],
    ownedStates: ['settings-form-loading-families', 'privacy-error'],
    ownedOverlays: ['data-erasure-and-account-deletion-modals'],
    queryState: [],
    legacyAliases: ['/settings/data-privacy'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'agreements',
    pathPattern: '/settings/legal/agreements',
    pageModule: 'app/(app)/settings/legal/agreements/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P6/P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['AgreementsSettingsPage', 'AgreementSettingsClient', 'DataTable', 'Drawer'],
    dataDependencies: ['agreements', 'agreement-rules'],
    ownedStates: ['settings-form-loading-families', 'agreements-empty', 'agreements-error'],
    ownedOverlays: ['agreement-upload-and-review-overlays'],
    queryState: ['status', 'selected'],
    legacyAliases: ['/settings/agreements'],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'billing',
    pathPattern: '/settings/billing',
    pageModule: 'app/(app)/settings/billing/page.tsx',
    shell: 'SettingsShell',
    archetype: 'P10',
    maturity: 'standardize',
    phase: 'p06',
    primaryComponents: ['BillingSettingsClient'],
    dataDependencies: ['billing-account', 'billing-plan', 'subscription-intents', 'usage-credit-receipts'],
    ownedStates: ['settings-form-loading-families', 'billing-unavailable', 'billing-error'],
    ownedOverlays: ['billing-plan-change-modal'],
    queryState: ['return'],
    legacyAliases: [],
    responsiveFamily: 'settings-setup',
  },
  {
    id: 'help-index',
    pathPattern: '/help',
    pageModule: 'app/(app)/help/page.tsx',
    shell: 'AppShell',
    archetype: 'P11',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['HelpCentre', 'PageFrame', 'Disclosure', 'ButtonLink'],
    dataDependencies: ['help-article-index'],
    ownedStates: ['help-empty', 'help-error'],
    ownedOverlays: [],
    queryState: ['q'],
    legacyAliases: [
      '/help/identity-matching',
      '/help/confidence-grades',
      '/help/how-it-works',
      '/help/integrations/siena',
      '/help/integrations/yuma',
    ],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'help-article',
    pathPattern: '/help/[articleSlug]',
    pageModule: 'app/(app)/help/[articleSlug]/page.tsx',
    shell: 'AppShell',
    archetype: 'P11',
    maturity: 'build',
    phase: 'p07',
    primaryComponents: ['HelpArticlePage', 'PageFrame', 'Surface', 'Disclosure'],
    dataDependencies: ['help-article-content'],
    ownedStates: ['help-article-unknown-slug', 'help-article-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'data-handling-explainer',
    pathPattern: '/legal/data-handling',
    pageModule: 'app/(public)/legal/data-handling/page.tsx',
    shell: 'PublicShell',
    archetype: 'P11',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6Legal'],
    dataDependencies: ['legal-document-content'],
    ownedStates: ['legal-document-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'data-processing-addendum',
    pathPattern: '/legal/dpa',
    pageModule: 'app/(public)/legal/dpa/page.tsx',
    shell: 'PublicShell',
    archetype: 'P11',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6Legal'],
    dataDependencies: ['legal-document-content'],
    ownedStates: ['legal-document-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'pilot-terms',
    pathPattern: '/legal/pilot-terms',
    pageModule: 'app/(public)/legal/pilot-terms/page.tsx',
    shell: 'PublicShell',
    archetype: 'P11',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6Legal'],
    dataDependencies: ['legal-document-content'],
    ownedStates: ['legal-document-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'privacy-policy',
    pathPattern: '/legal/privacy',
    pageModule: 'app/(public)/legal/privacy/page.tsx',
    shell: 'PublicShell',
    archetype: 'P11',
    maturity: 'standardize',
    phase: 'p07',
    primaryComponents: ['Challenge6Legal'],
    dataDependencies: ['legal-document-content'],
    ownedStates: ['legal-document-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'read-legal-help',
  },
  {
    id: 'controls-index-adapter',
    pathPattern: '/controls',
    pageModule: 'app/(app)/controls/page.tsx',
    shell: 'AppShell',
    archetype: 'P12',
    maturity: 'adapter',
    phase: 'p08',
    primaryComponents: ['ControlsIndexPage', 'preservedRedirectTarget'],
    dataDependencies: [],
    ownedStates: [],
    ownedOverlays: [],
    queryState: ['search', 'state', 'type', 'sort', 'selected'],
    legacyAliases: [],
    responsiveFamily: 'adapter',
  },
  {
    id: 'financials-index-adapter',
    pathPattern: '/financials',
    pageModule: 'app/(app)/financials/page.tsx',
    shell: 'AppShell',
    archetype: 'P12',
    maturity: 'adapter',
    phase: 'p08',
    primaryComponents: ['FinancialsIndexPage', 'preservedRedirectTarget'],
    dataDependencies: [],
    ownedStates: [],
    ownedOverlays: [],
    queryState: ['range', 'currency', 'source', 'status', 'search', 'sort', 'page'],
    legacyAliases: [],
    responsiveFamily: 'adapter',
  },
  {
    id: 'sources-index-adapter',
    pathPattern: '/sources',
    pageModule: 'app/(app)/sources/page.tsx',
    shell: 'AppShell',
    archetype: 'P12',
    maturity: 'adapter',
    phase: 'p08',
    primaryComponents: ['SourcesIndexPage', 'preservedRedirectTarget'],
    dataDependencies: [],
    ownedStates: [],
    ownedOverlays: [],
    queryState: ['status', 'category', 'q'],
    legacyAliases: [],
    responsiveFamily: 'adapter',
  },
  {
    id: 'customer-claims-adapter',
    pathPattern: '/customers/[id]/claims',
    pageModule: 'app/(app)/customers/[id]/claims/page.tsx',
    shell: 'AppShell',
    archetype: 'P12',
    maturity: 'adapter',
    phase: 'p08',
    primaryComponents: ['CustomerClaimReviewPage', 'preservedRedirectTarget'],
    dataDependencies: [],
    ownedStates: [],
    ownedOverlays: [],
    queryState: ['claimId', 'tab', 'investigationId'],
    legacyAliases: [],
    responsiveFamily: 'adapter',
  },
  {
    id: 'named-report-record-view',
    pathPattern: '/financials/reports/[reportId]',
    pageModule: 'app/(app)/financials/reports/[reportId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P9/P7',
    maturity: 'build',
    phase: 'p03',
    primaryComponents: ['NamedReportDetail', 'NamedReportAnalytics', 'ReportsScope', 'ChartFrame', 'DataTable'],
    dataDependencies: ['financial-report', 'report-records', 'financial-scope'],
    ownedStates: ['reports-and-records-loading', 'named-report-not-found', 'named-report-unavailable', 'named-report-error'],
    ownedOverlays: [],
    queryState: ['range', 'currency', 'page'],
    legacyAliases: [],
    responsiveFamily: 'overview-report',
  },
  {
    id: 'import-job-route',
    pathPattern: '/sources/imports/[jobId]',
    pageModule: 'app/(app)/sources/imports/[jobId]/page.tsx',
    shell: 'DetailShell',
    archetype: 'P7/P8',
    maturity: 'build',
    phase: 'p05',
    primaryComponents: ['ImportJobDetail', 'DataTable', 'StatusWithReason', 'PageFrame'],
    dataDependencies: ['import-job', 'import-mapping-snapshot', 'import-validation-rows'],
    ownedStates: ['import-job-loading', 'import-job-not-found', 'import-job-error'],
    ownedOverlays: [],
    queryState: [],
    legacyAliases: [],
    responsiveFamily: 'record-detail',
  },
] as const satisfies readonly SurfaceManifestEntry[];

export type SharedSurfaceFamily = {
  id: string;
  phase: ImplementationPhase;
  members: readonly string[];
  primaryComponents: readonly string[];
};

/** Owners for audited surfaces that intentionally span several routes. */
export const sharedSurfaceFamilies = [
  {
    id: 'shared:source-connection-routes',
    phase: 'p05',
    members: ['/sources/[sourceId]', '/sources/setup/[providerId]'],
    primaryComponents: ['ConnectionActions', 'Modal'],
  },
  {
    id: 'shared:app-shell',
    phase: 'p01',
    members: ['app/(app)/layout.tsx', 'app/(app)/loading.tsx'],
    primaryComponents: [
      'AuthenticatedDesignShell',
      'AuthenticatedSidebar',
      'WorkspaceSwitcher',
      'CommandPalette',
      'PageFrame',
      'DesktopRequiredBoundary',
    ],
  },
  {
    id: 'shared:operational-list-board',
    phase: 'p01',
    members: ['/work', '/controls/*', '/financials/*', '/sources/*'],
    primaryComponents: ['OperationalRouteSkeleton', 'DataTable', 'LoadingSkeleton'],
  },
  {
    id: 'shared:operational-detail',
    phase: 'p01',
    members: ['/cases/*', '/customers/*', '/financials/*', '/controls/*'],
    primaryComponents: ['OperationalRouteSkeleton', 'DetailPageShell', 'WorkbenchPage'],
  },
  {
    id: 'shared:connected-records',
    phase: 'p02',
    members: [
      '/orders/[id]',
      '/refunds/[id]',
      '/returns/[id]',
      '/shipments/[id]',
      '/tickets/[id]',
      '/disputes/[id]',
      '/financials/losses/[lossId]',
    ],
    primaryComponents: ['ConnectedObjectDetail', 'CommerceObjectRouteSkeleton', 'SupportObjectRouteSkeleton'],
  },
  {
    id: 'shared:commerce-object-routes',
    phase: 'p02',
    members: ['/orders/[id]', '/refunds/[id]', '/returns/[id]', '/shipments/[id]'],
    primaryComponents: ['CommerceObjectRouteSkeleton'],
  },
  {
    id: 'shared:support-object-routes',
    phase: 'p02',
    members: ['/tickets/[id]', '/disputes/[id]'],
    primaryComponents: ['SupportObjectRouteSkeleton'],
  },
  {
    id: 'shared:reports',
    phase: 'p03',
    members: ['/financials/reports', '/financials/reports/records', '/financials/reports/[reportId]'],
    primaryComponents: ['ChartFrame', 'DataTableServer', 'LoadingSkeleton'],
  },
  {
    id: 'shared:settings-configuration',
    phase: 'p06',
    members: ['/settings/*', '/sources/setup/*'],
    primaryComponents: ['SettingsPageShell', 'FormField', 'LoadingSkeleton'],
  },
  {
    id: 'shared:route-errors',
    phase: 'p08',
    members: ['app/**/error.tsx'],
    primaryComponents: ['OperationalRouteError', 'ErrorBoundaryUI'],
  },
  {
    id: 'shared:root',
    phase: 'p08',
    members: ['app/not-found.tsx', 'app/global-error.tsx'],
    primaryComponents: ['RecoveryShell', 'GlobalError'],
  },
] as const satisfies readonly SharedSurfaceFamily[];

export type AuditedSurfaceKind =
  | 'route'
  | 'overlay'
  | 'state'
  | 'loading'
  | 'not-found'
  | 'error';

export type AuditedSurfaceOwnership = {
  index: number;
  id: string;
  label: string;
  owner: string;
  kind: AuditedSurfaceKind;
  phase: ImplementationPhase;
};

type AuditedSurfaceRow = readonly [
  index: number,
  id: string,
  label: string,
  owner: string,
  kind: AuditedSurfaceKind,
  phase: ImplementationPhase,
];

const auditedSurfaceRows = [
  [1, 'marketing-landing', 'Marketing landing', '/landing', 'route', 'p07'],
  [2, 'pricing', 'Pricing', '/pricing', 'route', 'p07'],
  [3, 'interactive-product-demo', 'Interactive product demo', '/demo', 'route', 'p07'],
  [4, 'create-account', 'Create account', '/signup', 'route', 'p07'],
  [5, 'sign-in', 'Sign in', '/login', 'route', 'p07'],
  [6, 'request-password-reset', 'Request password reset', '/reset', 'route', 'p07'],
  [7, 'password-reset-sent-state', 'Password-reset sent state', '/reset', 'state', 'p07'],
  [8, 'set-new-password', 'Set new password', '/reset/update', 'route', 'p07'],
  [9, 'workspace-onboarding-store-profile', 'Workspace onboarding — store profile', '/onboarding', 'state', 'p07'],
  [10, 'workspace-onboarding-shopify-connection', 'Workspace onboarding — Shopify connection', '/onboarding', 'state', 'p07'],
  [11, 'workspace-onboarding-helpdesk-connection', 'Workspace onboarding — helpdesk connection', '/onboarding', 'state', 'p07'],
  [12, 'workspace-onboarding-setup-verified', 'Workspace onboarding — setup verified', '/onboarding', 'state', 'p07'],
  [13, 'overview-dashboard', 'Overview dashboard', '/overview', 'route', 'p02'],
  [14, 'overview-data-trust-details-modal', 'Overview data-trust details modal', '/overview', 'overlay', 'p02'],
  [15, 'overview-unavailable-and-no-work-states', 'Overview unavailable and no-work states', '/overview', 'state', 'p02'],
  [16, 'work-queue', 'Work queue', '/work', 'route', 'p02'],
  [17, 'integration-exception-resolution-drawer', 'Integration-exception resolution drawer', '/work', 'overlay', 'p02'],
  [18, 'saved-work-views', 'Saved Work views', '/work', 'state', 'p02'],
  [19, 'work-empty-search-states', 'Work empty/search states', '/work', 'state', 'p02'],
  [20, 'cases-registry', 'Cases registry', '/cases', 'route', 'p02'],
  [21, 'case-context-drawer', 'Case context drawer', '/cases', 'overlay', 'p02'],
  [22, 'cases-empty-filter-states', 'Cases empty/filter states', '/cases', 'state', 'p02'],
  [23, 'case-review-workbench', 'Case review workbench', '/cases/[caseId]', 'route', 'p02'],
  [24, 'record-or-reverse-merchant-decision-modals', 'Record or reverse merchant decision modals', '/cases/[caseId]', 'overlay', 'p02'],
  [25, 'investigation-request-modal', 'Investigation request modal', '/cases/[caseId]', 'overlay', 'p02'],
  [26, 'investigation-response-modal', 'Investigation response modal', '/cases/[caseId]', 'overlay', 'p02'],
  [27, 'investigation-lifecycle-action-modal', 'Investigation lifecycle action modal', '/cases/[caseId]', 'overlay', 'p02'],
  [28, 'responsibility-assessment-modal', 'Responsibility assessment modal', '/cases/[caseId]', 'overlay', 'p02'],
  [29, 'delivery-photo-finding-modal', 'Delivery-photo finding modal', '/cases/[caseId]', 'overlay', 'p02'],
  [30, 'customers-registry', 'Customers registry', '/customers', 'route', 'p02'],
  [31, 'customer-preview-drawer', 'Customer preview drawer', '/customers', 'overlay', 'p02'],
  [32, 'customers-empty-filter-states', 'Customers empty/filter states', '/customers', 'state', 'p02'],
  [33, 'customer-profile', 'Customer profile', '/customers/[id]', 'route', 'p02'],
  [34, 'customer-profile-access-blocked-state', 'Customer profile access-blocked state', '/customers/[id]', 'state', 'p02'],
  [35, 'build-evidence-package', 'Build evidence package', '/customers/[id]/evidence/new', 'route', 'p02'],
  [36, 'evidence-package-no-orders-no-cases-states', 'Evidence-package no-orders/no-cases states', '/customers/[id]/evidence/new', 'state', 'p02'],
  [37, 'order-detail', 'Order detail', '/orders/[id]', 'route', 'p02'],
  [38, 'refund-detail', 'Refund detail', '/refunds/[id]', 'route', 'p02'],
  [39, 'return-detail', 'Return detail', '/returns/[id]', 'route', 'p02'],
  [40, 'shipment-detail', 'Shipment detail', '/shipments/[id]', 'route', 'p02'],
  [41, 'support-ticket-detail', 'Support ticket detail', '/tickets/[id]', 'route', 'p02'],
  [42, 'dispute-detail', 'Dispute detail', '/disputes/[id]', 'route', 'p02'],
  [43, 'connected-record-not-found', 'Connected-record not found', 'shared:connected-records', 'not-found', 'p02'],
  [44, 'loss-ledger', 'Loss ledger', '/financials/losses', 'route', 'p03'],
  [45, 'loss-chart-ledger-unavailable-states', 'Loss chart/ledger unavailable states', '/financials/losses', 'state', 'p03'],
  [46, 'loss-detail', 'Loss detail', '/financials/losses/[lossId]', 'route', 'p03'],
  [47, 'write-off-outstanding-recovery-modal', 'Write off outstanding recovery modal', '/financials/losses/[lossId]', 'overlay', 'p03'],
  [48, 'recovery-board', 'Recovery board', '/financials/recovery', 'route', 'p03'],
  [49, 'confirm-recovery-action-modal', 'Confirm recovery action modal', '/financials/recovery', 'overlay', 'p03'],
  [50, 'recovery-board-empty-state', 'Recovery board empty state', '/financials/recovery', 'state', 'p03'],
  [51, 'recovery-detail', 'Recovery detail', '/financials/recovery/[recoveryId]', 'route', 'p03'],
  [52, 'reconciliation-exception-workspace', 'Reconciliation exception workspace', '/financials/reconciliation', 'route', 'p03'],
  [53, 'reconciliation-loading-empty-states', 'Reconciliation loading/empty states', '/financials/reconciliation', 'state', 'p03'],
  [54, 'financial-reports', 'Financial reports', '/financials/reports', 'route', 'p03'],
  [55, 'report-supporting-records', 'Report supporting records', '/financials/reports/records', 'route', 'p03'],
  [56, 'named-report-record-view', 'Named report record view', '/financials/reports/[reportId]', 'route', 'p03'],
  [57, 'payout-rules-registry', 'Payout rules registry', '/controls/rules', 'route', 'p04'],
  [58, 'rule-builder-drawer', 'Rule builder drawer', '/controls/rules', 'overlay', 'p04'],
  [59, 'rules-empty-state', 'Rules empty state', '/controls/rules', 'state', 'p04'],
  [60, 'rule-version-workbench', 'Rule version workbench', '/controls/rules/[ruleId]', 'route', 'p04'],
  [61, 'rule-simulation-and-publication-modals', 'Rule simulation and publication modals', '/controls/rules/[ruleId]', 'overlay', 'p04'],
  [62, 'recovery-rulebook', 'Recovery rulebook', '/controls/rules/recovery', 'route', 'p04'],
  [63, 'partner-and-recovery-rule-modals', 'Partner and recovery-rule modals', '/controls/rules/recovery', 'overlay', 'p04'],
  [64, 'flows-registry', 'Flows registry', '/controls/flows', 'route', 'p04'],
  [65, 'new-flow-draft-modal', 'New flow draft modal', '/controls/flows', 'overlay', 'p04'],
  [66, 'flows-empty-state', 'Flows empty state', '/controls/flows', 'state', 'p04'],
  [67, 'flow-version-workbench', 'Flow version workbench', '/controls/flows/[flowId]', 'route', 'p04'],
  [68, 'flow-edit-test-and-publication-modals', 'Flow edit, test and publication modals', '/controls/flows/[flowId]', 'overlay', 'p04'],
  [69, 'flow-runs-registry', 'Flow runs registry', '/controls/flows/runs', 'route', 'p04'],
  [70, 'flow-run-detail', 'Flow run detail', '/controls/flows/runs/[runId]', 'route', 'p04'],
  [71, 'connected-sources', 'Connected sources', '/sources/connected', 'route', 'p05'],
  [72, 'source-catalogue', 'Source catalogue', '/sources/browse', 'route', 'p05'],
  [73, 'source-detail', 'Source detail', '/sources/[sourceId]', 'route', 'p05'],
  [74, 'connection-and-disconnection-modals', 'Connection and disconnection modals', 'shared:source-connection-routes', 'overlay', 'p05'],
  [75, 'connect-shopify-modal', 'Connect Shopify modal', '/sources/setup/[providerId]', 'overlay', 'p05'],
  [76, 'csv-imports', 'CSV imports', '/sources/imports', 'route', 'p05'],
  [77, 'import-validation-empty-states', 'Import validation/empty states', '/sources/imports', 'state', 'p05'],
  [78, 'import-job-route', 'Import job route', '/sources/imports/[jobId]', 'route', 'p05'],
  [79, 'provider-specific-connector-setup', 'Provider-specific connector setup', '/sources/setup/[providerId]', 'route', 'p05'],
  [80, 'generic-seven-step-source-setup', 'Generic seven-step source setup', '/sources/setup/[providerId]', 'state', 'p05'],
  [81, 'shipbob-channel-selection', 'ShipBob channel selection', '/sources/setup/shipbob/select', 'route', 'p05'],
  [82, 'account-and-appearance', 'Account and appearance', '/settings/workspace/account', 'route', 'p06'],
  [83, 'team-management', 'Team management', '/settings/workspace/team', 'route', 'p06'],
  [84, 'invite-member-and-transfer-ownership-modals', 'Invite member and transfer ownership modals', '/settings/workspace/team', 'overlay', 'p06'],
  [85, 'platform-defaults', 'Platform defaults', '/settings/product/platform', 'route', 'p06'],
  [86, 'notification-preferences', 'Notification preferences', '/settings/product/notifications', 'route', 'p06'],
  [87, 'developer-api-access', 'Developer API access', '/settings/developers/api-access', 'route', 'p06'],
  [88, 'create-reveal-and-revoke-api-key-modals', 'Create/reveal and revoke API key modals', '/settings/developers/api-access', 'overlay', 'p06'],
  [89, 'audit-trail', 'Audit trail', '/settings/governance/audit-trail', 'route', 'p06'],
  [90, 'data-privacy', 'Data privacy', '/settings/legal/data-privacy', 'route', 'p06'],
  [91, 'agreements', 'Agreements', '/settings/legal/agreements', 'route', 'p06'],
  [92, 'billing', 'Billing', '/settings/billing', 'route', 'p06'],
  [93, 'notifications-inbox', 'Notifications inbox', '/notifications', 'route', 'p07'],
  [94, 'notifications-empty-states', 'Notifications empty states', '/notifications', 'state', 'p07'],
  [95, 'search-route', 'Search route', '/search', 'route', 'p07'],
  [96, 'global-command-palette', 'Global command palette', 'shared:app-shell', 'overlay', 'p01'],
  [97, 'help-index', 'Help index', '/help', 'route', 'p07'],
  [98, 'help-article', 'Help article', '/help/[articleSlug]', 'route', 'p07'],
  [99, 'privacy-policy', 'Privacy policy', '/legal/privacy', 'route', 'p07'],
  [100, 'data-handling-explainer', 'Data handling explainer', '/legal/data-handling', 'route', 'p07'],
  [101, 'data-processing-addendum', 'Data processing addendum', '/legal/dpa', 'route', 'p07'],
  [102, 'pilot-terms', 'Pilot terms', '/legal/pilot-terms', 'route', 'p07'],
  [103, 'authenticated-route-loading-shell', 'Authenticated route loading shell', 'shared:app-shell', 'loading', 'p01'],
  [104, 'overview-dashboard-loading', 'Overview dashboard loading', '/overview', 'loading', 'p02'],
  [105, 'operational-list-board-loading-skeleton', 'Operational list/board loading skeleton', 'shared:operational-list-board', 'loading', 'p01'],
  [106, 'operational-detail-loading-skeleton', 'Operational detail loading skeleton', 'shared:operational-detail', 'loading', 'p01'],
  [107, 'cases-registry-loading', 'Cases registry loading', '/cases', 'loading', 'p02'],
  [108, 'customers-registry-loading', 'Customers registry loading', '/customers', 'loading', 'p02'],
  [109, 'evidence-package-builder-loading', 'Evidence-package builder loading', '/customers/[id]/evidence/new', 'loading', 'p02'],
  [110, 'commerce-object-loading', 'Commerce-object loading', 'shared:commerce-object-routes', 'loading', 'p02'],
  [111, 'support-object-loading', 'Support-object loading', 'shared:support-object-routes', 'loading', 'p02'],
  [112, 'reports-and-records-loading', 'Reports and records loading', 'shared:reports', 'loading', 'p03'],
  [113, 'settings-form-loading-families', 'Settings/form loading families', 'shared:settings-configuration', 'loading', 'p06'],
  [114, 'onboarding-loading', 'Onboarding loading', '/onboarding', 'loading', 'p07'],
  [115, 'notifications-loading', 'Notifications loading', '/notifications', 'loading', 'p07'],
  [116, 'authenticated-not-found', 'Authenticated not-found', 'shared:app-shell', 'not-found', 'p01'],
  [117, 'root-not-found', 'Root not-found', 'shared:root', 'not-found', 'p08'],
  [118, 'route-error-boundaries', 'Route error boundaries', 'shared:route-errors', 'error', 'p08'],
  [119, 'root-global-error', 'Root global error', 'shared:root', 'error', 'p08'],
] as const satisfies readonly AuditedSurfaceRow[];

export const auditedSurfaceOwnership: readonly AuditedSurfaceOwnership[] = auditedSurfaceRows.map(
  ([index, id, label, owner, kind, phase]) => ({ index, id, label, owner, kind, phase }),
);

/** Explicit visual boundary for every concrete page module. */
export const visualDispositionBySurfaceId = Object.fromEntries(
  surfaceManifest.map((entry) => [
    entry.id,
    entry.maturity === 'adapter' ? 'adapter' : 'replace',
  ]),
) as Readonly<Record<string, VisualDisposition>>;

const scopedAuditedRows = auditedSurfaceOwnership;
const scenarioContracts = new Map<string, ScenarioContract>();

function addScenario(contract: ScenarioContract) {
  if (!scenarioContracts.has(contract.id)) scenarioContracts.set(contract.id, contract);
}

for (const entry of surfaceManifest) {
  const disposition = visualDispositionBySurfaceId[entry.id];
  if (disposition === 'frozen') continue;
  addScenario({
    id: entry.id,
    owner: entry.pathPattern,
    pageModule: entry.pageModule,
    kind: disposition === 'adapter' ? 'adapter' : 'route',
    disposition,
    viewportFamily: entry.responsiveFamily,
    activationRecipe: disposition === 'adapter' ? 'Navigate with representative query state and verify the canonical destination.' : 'Navigate to the canonical route with a safe local fixture.',
    readiness: disposition === 'adapter' ? 'redirect-complete' : 'visual-ready',
  });
  for (const id of entry.ownedStates) {
    addScenario({ id, owner: entry.pathPattern, pageModule: entry.pageModule, kind: id.includes('loading') ? 'loading' : 'state', disposition: 'replace', viewportFamily: entry.responsiveFamily, activationRecipe: `Activate declared state ${id} with a safe local fixture or deterministic route state.`, readiness: 'visual-ready' });
  }
  for (const id of entry.ownedOverlays) {
    addScenario({ id, owner: entry.pathPattern, pageModule: entry.pageModule, kind: 'overlay', disposition: 'replace', viewportFamily: entry.responsiveFamily, activationRecipe: `Open ${id} without confirming a destructive or external mutation.`, readiness: 'visual-ready' });
  }
}

for (const surface of scopedAuditedRows) {
  if (scenarioContracts.has(surface.id)) continue;
  const owner = surfaceManifest.find((entry) => entry.pathPattern === surface.owner);
  addScenario({ id: surface.id, owner: surface.owner, pageModule: owner?.pageModule ?? null, kind: surface.kind, disposition: 'replace', viewportFamily: owner?.responsiveFamily ?? 'shared-product', activationRecipe: `Activate audited ${surface.kind} ${surface.id} with a safe local fixture.`, readiness: 'visual-ready' });
}

/** Minimum complete contract ledger before runtime-discovered menus and states. */
export const scenarioLedger = [...scenarioContracts.values()] as readonly ScenarioContract[];

export type AdapterDisposition = {
  pathPattern: string;
  pageModule: string | null;
  currentBehavior: string;
  targetDisposition: string;
  phase: ImplementationPhase;
};

export type SpecializedGapDisposition = {
  id: `g${number}`;
  owner: string;
  status: 'implemented' | 'intentionally-unbuilt';
  evidence: readonly string[];
  phase: ImplementationPhase | 'future-brief';
};

/** Guardrails for redirect-only routes and the two adapters upgraded later. */
export const adapterDispositions = [
  {
    pathPattern: '/',
    pageModule: null,
    currentBehavior: 'Redirects to /landing through LEGACY_UI_REDIRECTS.',
    targetDisposition: 'Preserve the redirect and do not create duplicate home UI.',
    phase: 'p08',
  },
  {
    pathPattern: '/controls',
    pageModule: 'app/(app)/controls/page.tsx',
    currentBehavior: 'Redirects to /controls/rules while preserving rule filter and selection query state.',
    targetDisposition: 'Preserve the canonical redirect and its URL-backed operating context.',
    phase: 'p08',
  },
  {
    pathPattern: '/financials',
    pageModule: 'app/(app)/financials/page.tsx',
    currentBehavior: 'Redirects to /financials/losses while preserving financial scope and registry query state.',
    targetDisposition: 'Preserve the canonical redirect and its URL-backed financial context.',
    phase: 'p08',
  },
  {
    pathPattern: '/sources',
    pageModule: 'app/(app)/sources/page.tsx',
    currentBehavior: 'Redirects to /sources/connected while preserving source filter query state.',
    targetDisposition: 'Preserve the canonical redirect and its URL-backed source context.',
    phase: 'p08',
  },
  {
    pathPattern: '/customers/[id]/claims',
    pageModule: 'app/(app)/customers/[id]/claims/page.tsx',
    currentBehavior: 'With a valid claimId, opens that case with a safe customer return; otherwise opens the customer cases section.',
    targetDisposition: 'Validate the target, preserve case query state and do not build a second claims layout.',
    phase: 'p08',
  },
  {
    pathPattern: '/financials/reports/[reportId]',
    pageModule: 'app/(app)/financials/reports/[reportId]/page.tsx',
    currentBehavior: 'Renders the P03 named-report analytical detail with current scope, run metadata and linked supporting records.',
    targetDisposition: 'P03 dedicated named-report detail implemented; persisted owner, schedule and delivery actions remain unavailable until a saved-report backend exists.',
    phase: 'p03',
  },
  {
    pathPattern: '/sources/imports/[jobId]',
    pageModule: 'app/(app)/sources/imports/[jobId]/page.tsx',
    currentBehavior: 'Loads the merchant-scoped CSV job and renders its immutable mapping, validation errors and outcome.',
    targetDisposition: 'Implemented in P05 as the G1 import-job detail contract.',
    phase: 'p05',
  },
] as const satisfies readonly AdapterDisposition[];

/**
 * P08 handoff for section 21. G1-G8 must already be implemented by their
 * owning phases; G9 remains deliberately absent until a separate internal
 * product brief defines its roles, tenancy and audit boundaries.
 */
export const specializedGapDispositions = [
  {
    id: 'g1',
    owner: '/sources/imports/[jobId]',
    status: 'implemented',
    evidence: ['components/imports/ImportJobDetail.tsx', 'app/api/imports/[jobId]/errors/route.ts'],
    phase: 'p05',
  },
  {
    id: 'g2',
    owner: '/search',
    status: 'implemented',
    evidence: ['components/search/WorkspaceSearch.tsx', 'components/layout/commandPaletteFetch.ts'],
    phase: 'p07',
  },
  {
    id: 'g3',
    owner: '/sources/setup/[providerId]',
    status: 'implemented',
    evidence: ['components/sources/SourceSetupWizard.tsx'],
    phase: 'p05',
  },
  {
    id: 'g4',
    owner: '/help/[articleSlug]',
    status: 'implemented',
    evidence: ['app/(app)/help/[articleSlug]/page.tsx'],
    phase: 'p07',
  },
  {
    id: 'g5',
    owner: '/financials/reports/[reportId]',
    status: 'implemented',
    evidence: ['components/reports/NamedReportDetail.tsx'],
    phase: 'p03',
  },
  {
    id: 'g6',
    owner: '/financials/reconciliation',
    status: 'implemented',
    evidence: ['components/exceptions/ExceptionQueue.tsx'],
    phase: 'p03',
  },
  {
    id: 'g7',
    owner: '/controls/flows/runs/[runId]',
    status: 'implemented',
    evidence: ['components/rules/FlowRunTrace.tsx'],
    phase: 'p04',
  },
  {
    id: 'g8',
    owner: '/sources/browse',
    status: 'implemented',
    evidence: ['app/(app)/sources/SourceConnectionsPage.tsx', 'components/sources/SourcesOperations.tsx'],
    phase: 'p05',
  },
  {
    id: 'g9',
    owner: 'app/(internal)',
    status: 'intentionally-unbuilt',
    evidence: ['app/(internal)/layout.tsx'],
    phase: 'future-brief',
  },
] as const satisfies readonly SpecializedGapDisposition[];

export const SURFACE_MANIFEST_EXPECTED_PAGE_COUNT = 64;
export const SURFACE_MANIFEST_EXPECTED_AUDITED_SURFACE_COUNT = 119;
export const SURFACE_MANIFEST_EXPECTED_SCENARIO_COUNT = 222;
export const SURFACE_MANIFEST_EXPECTED_VISUAL_SCENARIO_COUNT = 218;
export const SURFACE_MANIFEST_EXPECTED_ADAPTER_SCENARIO_COUNT = 4;
export const SURFACE_MANIFEST_EXPECTED_PHASE_COUNTS = {
  p01: 0,
  p02: 13,
  p03: 8,
  p04: 7,
  p05: 7,
  p06: 9,
  p07: 16,
  p08: 4,
} as const satisfies Record<ImplementationPhase, number>;
