import {test,expect,type Page} from '@playwright/test';
import {DEMO_VERSION,demoStorageKey} from '@/lib/demo/merchantCaseV1';
const choices=[['legitimate','Refund','refund'],['legitimate','Replace','replace'],['legitimate','Request review','review'],['duplicate','No additional payout','no-payout'],['duplicate','Escalate','escalate'],['duplicate','Goodwill exception','goodwill'],['recoverable','Refund and prepare recovery','refund-recovery'],['recoverable','Request review','review']] as const;
async function metric(page:Page,label:string,value:string){await expect(page.locator('dt',{hasText:label}).locator('xpath=following-sibling::dd[1]')).toHaveText(value);}
for(const width of [1440,390])for(const [caseId,label,choice] of choices)test(`Demo ${caseId} ${choice} causal branch · ${width}`,async({page,context},info)=>{
  await context.clearCookies();await page.setViewportSize({width,height:844});const mutations:string[]=[];const external:string[]=[];const errors:string[]=[];
  page.on('request',r=>{const url=new URL(r.url());if(!['GET','HEAD','OPTIONS'].includes(r.method()))mutations.push(r.method()+' '+url.pathname);if(url.protocol.startsWith('http')&&!['localhost','127.0.0.1'].includes(url.hostname))external.push(url.origin);});page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`/demo?case=${caseId}&step=inspect`);await expect(page.locator('main')).toHaveAttribute('data-demo-case',caseId);await page.getByRole('button',{name:'Compare choices',exact:true}).click();const opener=page.getByRole('button',{name:`Review ${label.toLowerCase()}`,exact:true});await opener.click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(key=>localStorage.getItem(key),demoStorageKey(caseId))).toBeNull();
  await opener.click();const confirm=dialog.getByRole('button',{name:'Confirm simulated decision',exact:true});if(choice==='goodwill'){await expect(confirm).toBeDisabled();await dialog.getByLabel('Goodwill rationale (required)',{exact:true}).fill('Fictional exception review; another concession is intentional.');}await confirm.click();await expect(page.locator('main')).toHaveAttribute('data-demo-step','outcome');await metric(page,'Total refunds observed (sample)',caseId==='duplicate'?'£128.00':'£0.00');
  if(['refund','goodwill','refund-recovery'].includes(choice)){const simulate=page.getByRole('button',{name:'Simulate refund observed',exact:true});await simulate.click();await expect(simulate).toBeDisabled();await metric(page,'Total refunds observed (sample)',caseId==='duplicate'?'£256.00':caseId==='recoverable'?'£248.00':'£96.00');}
  if(choice==='replace'){await expect(page.getByText(/£33 GBP authorised cost budget/).first()).toBeVisible();await metric(page,'Replacement dispatch (sample)','Not observed');await page.getByRole('button',{name:'Simulate replacement dispatched',exact:true}).click();await metric(page,'Replacement dispatch (sample)','Observed in simulation');}
  if(choice==='refund-recovery'){
    for(const stage of ['Submitted','Provider approved','Received','Matched','Reconciled']){await page.getByRole('button',{name:`Simulate recovery ${stage.toLowerCase()}`,exact:true}).click();await metric(page,'Recovery stage (sample)',stage);await metric(page,'Recovery received (sample)',['Received','Matched','Reconciled'].includes(stage)?'£150.00':'£0.00');await metric(page,'Recovery reconciled (sample)',stage==='Reconciled'?'£150.00':'£0.00');await metric(page,'Unrecovered refund balance (sample)',stage==='Reconciled'?'£98.00':'£248.00');}
  }
  if(['review','escalate'].includes(choice)){await expect(page.getByText(/This case remains unresolved/)).toBeVisible();await expect(page.getByText('Sample walkthrough complete',{exact:true})).toHaveCount(0);}else await expect(page.getByText('Sample walkthrough complete',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'2. Decide',exact:true}).click();const reviews=page.getByRole('button',{name:/^Review /});for(let i=0;i<await reviews.count();i++)await expect(reviews.nth(i)).toBeDisabled();await page.getByRole('button',{name:'3. Outcome',exact:true}).click();await page.reload();await expect(page.locator('main')).toHaveAttribute('data-demo-step','outcome');
  const stored=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),demoStorageKey(caseId));expect(stored.version).toBe(DEMO_VERSION);expect(stored.progress.decision).toBe(choice);
  await page.mouse.wheel(0,10000);await expect(page.getByRole('button',{name:'Reset this case',exact:true})).toBeInViewport();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:info.outputPath(`${caseId}-${choice}.png`)});expect(mutations).toEqual([]);expect(external).toEqual([]);expect(errors).toEqual([]);
});

for(const width of [1440,390])test(`Demo URL, history and per-case storage isolation · ${width}`,async({page,context},info)=>{
  await context.clearCookies();await page.setViewportSize({width,height:844});
  await page.goto('/demo?case=unknown&step=outcome');await expect(page.locator('main')).toHaveAttribute('data-demo-case','legitimate');await expect(page.locator('main')).toHaveAttribute('data-demo-step','inspect');
  await page.evaluate(({key,version})=>localStorage.setItem(key,JSON.stringify({version:version+'-obsolete',caseId:'legitimate',progress:{decision:'refund',refundObserved:true,recovery:5}})),{key:demoStorageKey('legitimate'),version:DEMO_VERSION});
  await page.goto('/demo?case=legitimate&step=recovery');await expect(page.locator('main')).toHaveAttribute('data-demo-step','decide');await expect(page.getByText('No decision has been made for this case. Review and confirm a choice before opening Outcome.',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Review refund',exact:true}).click();await page.getByRole('button',{name:'Confirm simulated decision',exact:true}).click();const kept=await page.evaluate(key=>localStorage.getItem(key),demoStorageKey('legitimate'));
  await page.getByRole('button',{name:'Duplicate payout',exact:true}).click();await page.getByRole('button',{name:'Compare choices',exact:true}).click();await page.getByRole('button',{name:'Review no additional payout',exact:true}).click();await page.getByRole('button',{name:'Confirm simulated decision',exact:true}).click();
  await page.goBack();await expect(page.locator('main')).toHaveAttribute('data-demo-step','decide');await expect(page.getByRole('button',{name:'Review no additional payout',exact:true})).toBeDisabled();await page.goForward();await expect(page.locator('main')).toHaveAttribute('data-demo-step','outcome');
  await page.getByRole('button',{name:'Reset this case',exact:true}).click();await expect(page.locator('main')).toHaveAttribute('data-demo-step','inspect');expect(await page.evaluate(key=>localStorage.getItem(key),demoStorageKey('duplicate'))).toBeNull();expect(await page.evaluate(key=>localStorage.getItem(key),demoStorageKey('legitimate'))).toBe(kept);
  await page.getByRole('button',{name:'Legitimate claim',exact:true}).click();await page.getByRole('button',{name:'3. Outcome',exact:true}).click();await expect(page.getByRole('heading',{name:'Simulated decision: Refund',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Simulated decision: Refund',exact:true})).toBeVisible();await metric(page,'Total refunds observed (sample)','£0.00');
  await page.goto('/demo?case=duplicate&step=inspect&unexpected=1');await expect(page.locator('main')).toHaveAttribute('data-demo-case','legitimate');await expect(page.locator('main')).toHaveAttribute('data-demo-step','inspect');await page.screenshot({path:info.outputPath('demo-url-isolation.png')});
});

test('Demo recovery can reconcile before the refund without fabricating payment',async({page,context})=>{
  await context.clearCookies();await page.goto('/demo?case=recoverable&step=decide');await page.getByRole('button',{name:'Review refund and prepare recovery',exact:true}).click();await page.getByRole('button',{name:'Confirm simulated decision',exact:true}).click();
  for(const stage of ['submitted','provider approved','received','matched','reconciled'])await page.getByRole('button',{name:`Simulate recovery ${stage}`,exact:true}).click();
  await metric(page,'Total refunds observed (sample)','£0.00');await metric(page,'Recovery reconciled (sample)','£150.00');await metric(page,'Unrecovered refund balance (sample)','-£150.00');await expect(page.getByText('Sample walkthrough complete',{exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Simulate refund observed',exact:true}).click();await metric(page,'Unrecovered refund balance (sample)','£98.00');await expect(page.getByText('Sample walkthrough complete',{exact:true})).toBeVisible();
});
