import { expect, test, type Page, type TestInfo } from '@playwright/test';
import { createClient as createSupabaseClient } from '@supabase/supabase-js';
import { createServerClient } from '@supabase/ssr';
import fs from 'node:fs';
import path from 'node:path';
import { scenarioLedger } from '@/lib/surfaces/manifest';

const ROOT = path.join(process.cwd(), 'artifacts', 'full-app-acceptance-2026-08-30');
const manifest = new Map(scenarioLedger.map((scenario) => [scenario.id, scenario]));
const variants = [{ id: 'mobile-light', width: 390, height: 844 }, { id: 'desktop-light', width: 1440, height: 900 }] as const;
const ids = ['signup-submitting', 'signup-error', 'login-submitting', 'login-error', 'password-reset-sent-state', 'password-reset-error', 'reset-update-invalid-session', 'reset-update-success', 'reset-update-error'] as const;
for (const id of ids) if (!manifest.has(id)) throw new Error(`Missing P07 auth scenario ${id}`);
type ScenarioId = typeof ids[number];
type Evidence = { id: string; viewport: string; screenshot: string; finalUrl: string; mutationReceipt: Record<string, unknown> | null; consoleErrors: string[]; pageErrors: string[]; failedRequests: string[]; expectedDiagnostics: string[] };
const evidence = new Map<ScenarioId, Evidence[]>();
function directory(id: ScenarioId) { const target = path.join(ROOT, 'scenarios', id); fs.mkdirSync(target, { recursive: true }); return target; }
async function screenshot(page: Page, id: ScenarioId, variant: string) { const target = path.join(directory(id), `${variant}.png`); await page.screenshot({ path: target, fullPage: true }); return path.relative(ROOT, target); }
function observe(page: Page, origin: string) { const consoleErrors: string[] = []; const pageErrors: string[] = []; const failedRequests: string[] = []; const expectedDiagnostics: string[] = []; page.on('console', (message) => { if (message.type() !== 'error') return; const value = message.text(); if (value.includes('503 (Service Unavailable)')) expectedDiagnostics.push(value); else consoleErrors.push(value); }); page.on('pageerror', (error) => pageErrors.push(error.message)); page.on('requestfailed', (request) => { const failure = request.failure()?.errorText ?? 'failed'; if (request.url().startsWith(origin) && failure !== 'net::ERR_ABORTED') failedRequests.push(`${request.method()} ${new URL(request.url()).pathname}: ${failure}`); }); return { consoleErrors, pageErrors, failedRequests, expectedDiagnostics }; }
function record(id: ScenarioId, entry: Evidence) { evidence.set(id, [...(evidence.get(id) ?? []), entry]); }
function localAdmin() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error('Local Supabase admin environment is required.'); if (process.env.RELEASE_E2E_LOCAL !== '1' || process.env.VERCEL_ENV === 'production' || !['127.0.0.1','localhost','::1','[::1]'].includes(new URL(url).hostname)) throw new Error('Disposable recovery users require guarded loopback Supabase.'); return createSupabaseClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
async function deleteRecoveryUser(admin: ReturnType<typeof localAdmin>, userId: string) {
  const removed = await admin.auth.admin.deleteUser(userId);
  if (removed.error) throw removed.error;
  const check = await admin.auth.admin.getUserById(userId);
  if (check.data.user || check.error?.status !== 404) throw new Error('Disposable recovery user cleanup could not be verified.');
}
test.beforeEach(({}, info) => {
  if (process.env.RELEASE_E2E_LOCAL !== '1' || !['127.0.0.1','localhost','::1','[::1]'].includes(new URL(String(info.project.use.baseURL)).hostname)) throw new Error('Auth-state checks require a loopback app.');
});
async function recoveryLink(baseURL: string, suffix: string) { const admin = localAdmin(); const url = process.env.NEXT_PUBLIC_SUPABASE_URL!; const publicKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY; if (!publicKey) throw new Error('Local Supabase public key is required.'); const email = `faa7-reset-${suffix}-${crypto.randomUUID()}@example.invalid`; const password = `Before-${crypto.randomUUID()}-8`; const created = await admin.auth.admin.createUser({ email, password, email_confirm: true, user_metadata: { fixture: 'forensic-auth-recovery', localOnly: true } }); if (created.error || !created.data.user) throw created.error ?? new Error('Disposable recovery user was not created.'); const generated = await admin.auth.admin.generateLink({ type: 'recovery', email, options: { redirectTo: `${baseURL}/reset/update` } }); const tokenHash = generated.data.properties?.hashed_token; if (generated.error || !tokenHash) { await deleteRecoveryUser(admin, created.data.user.id); throw generated.error ?? new Error('Disposable recovery link was not generated.'); } let cookies: Array<{ name: string; value: string }> = []; const verifier = createServerClient(url, publicKey, { cookies: { getAll: () => [], setAll: (next) => { cookies = next.map(({ name, value }) => ({ name, value })); } } }); const verified = await verifier.auth.verifyOtp({ token_hash: tokenHash, type: 'recovery' }); if (verified.error || !verified.data.session || !cookies.length) { await deleteRecoveryUser(admin, created.data.user.id); throw verified.error ?? new Error('Disposable recovery session was not created.'); } return { admin, userId: created.data.user.id, email, cookies }; }

test.describe('FAA-7 public auth states', () => {
  for (const variant of variants) {
    test(`signup states · ${variant.id}`, async ({ page, context }, info: TestInfo) => {
      const base = new URL(String(info.project.use.baseURL)); await context.clearCookies(); await page.setViewportSize({ width: variant.width, height: variant.height }); const runtime = observe(page, base.origin);
      await page.goto('/signup'); await page.getByRole('button', { name: 'Create workspace' }).click(); await expect(page.locator('[data-state-id="signup-error"]')).toBeVisible(); const errorShot = await screenshot(page, 'signup-error', variant.id);
      record('signup-error', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: errorShot, finalUrl: new URL(page.url()).pathname, mutationReceipt: null, ...runtime });
      await page.route('**/auth/v1/signup**', async (route) => { await new Promise((resolve) => setTimeout(resolve, 5_000)); await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ msg: 'local intercepted request' }) }); });
      await page.getByLabel('Work email').fill(`faa7-signup-${crypto.randomUUID()}@example.invalid`); await page.locator('input[name="password"]').fill('Acceptance-password-8'); await page.locator('input[name="confirm-password"]').fill('Acceptance-password-8'); await page.getByRole('button', { name: 'Create workspace' }).click(); await expect(page.locator('[data-state-id="signup-submitting"]')).toBeVisible(); const submitShot = await screenshot(page, 'signup-submitting', variant.id);
      expect(runtime.consoleErrors).toEqual([]); expect(runtime.pageErrors).toEqual([]); expect(runtime.failedRequests).toEqual([]); record('signup-submitting', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: submitShot, finalUrl: new URL(page.url()).pathname, mutationReceipt: { request: 'POST loopback auth signup intercepted before execution', externalEmailSent: false, persistedAccount: false }, ...runtime });
    });

    test(`login states · ${variant.id}`, async ({ page, context }, info: TestInfo) => {
      const base = new URL(String(info.project.use.baseURL)); await context.clearCookies(); await page.setViewportSize({ width: variant.width, height: variant.height }); const runtime = observe(page, base.origin);
      await page.goto('/login'); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.locator('[data-state-id="login-error"]')).toBeVisible(); record('login-error', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, 'login-error', variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: null, ...runtime });
      await page.route('**/auth/v1/token**', async (route) => { await new Promise((resolve) => setTimeout(resolve, 5_000)); await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error_description: 'local intercepted request' }) }); });
      await page.locator('#login-email').fill(`faa7-login-${crypto.randomUUID()}@example.invalid`); await page.locator('#login-password').fill('Acceptance-password-8'); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.locator('[data-state-id="login-submitting"]')).toBeVisible(); expect(runtime.consoleErrors).toEqual([]); expect(runtime.pageErrors).toEqual([]); expect(runtime.failedRequests).toEqual([]); record('login-submitting', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, 'login-submitting', variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: { request: 'POST loopback password grant intercepted before execution', persistedSession: false }, ...runtime });
    });

    test(`password reset request states · ${variant.id}`, async ({ page, context }, info: TestInfo) => {
      const base = new URL(String(info.project.use.baseURL)); await context.clearCookies(); await page.setViewportSize({ width: variant.width, height: variant.height }); const runtime = observe(page, base.origin); const email = `faa7-reset-request-${crypto.randomUUID()}@example.invalid`;
      await page.route('**/auth/v1/recover**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: '{}' })); await page.goto('/reset'); await page.getByLabel('Email').fill(email); await page.getByRole('button', { name: 'Send the link' }).click(); await expect(page.locator('[data-state-id="password-reset-sent-state"]')).toBeVisible(); record('password-reset-sent-state', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, 'password-reset-sent-state', variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: { response: 'synthetic loopback success intercepted in browser', externalEmailSent: false }, ...runtime });
      await page.unroute('**/auth/v1/recover**'); await page.route('**/auth/v1/recover**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ msg: 'local acceptance failure' }) })); await page.goto('/reset'); await page.getByLabel('Email').fill(email); await page.getByRole('button', { name: 'Send the link' }).click(); await expect(page.locator('[data-state-id="password-reset-error"]')).toBeVisible(); expect(runtime.consoleErrors).toEqual([]); expect(runtime.pageErrors).toEqual([]); expect(runtime.failedRequests).toEqual([]); record('password-reset-error', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, 'password-reset-error', variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: { response: 'synthetic loopback failure intercepted in browser', externalEmailSent: false }, ...runtime });
    });

    test(`reset update invalid · ${variant.id}`, async ({ page, context }, info: TestInfo) => {
      const base = new URL(String(info.project.use.baseURL)); await context.clearCookies(); await page.setViewportSize({ width: variant.width, height: variant.height }); const runtime = observe(page, base.origin); await page.goto('/reset/update'); await expect(page.locator('[data-state-id="reset-update-invalid-session"]')).toBeVisible({ timeout: 15_000 }); expect(runtime.consoleErrors).toEqual([]); expect(runtime.pageErrors).toEqual([]); expect(runtime.failedRequests).toEqual([]); record('reset-update-invalid-session', { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, 'reset-update-invalid-session', variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: null, ...runtime });
    });

    for (const outcome of ['success', 'error'] as const) test(`reset update ${outcome} · ${variant.id}`, async ({ page, context }, info: TestInfo) => {
      const base = new URL(String(info.project.use.baseURL)); await context.clearCookies(); await page.setViewportSize({ width: variant.width, height: variant.height }); const runtime = observe(page, base.origin); const disposable = await recoveryLink(base.origin, `${outcome}-${variant.id}`);
      try {
        if (outcome === 'error') await page.route('**/auth/v1/user**', async (route) => route.request().method() === 'PUT' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ msg: 'local acceptance update failure' }) }) : route.continue());
        await context.addCookies(disposable.cookies.map((cookie) => ({ ...cookie, url: base.origin }))); await page.goto('/reset/update', { waitUntil: 'domcontentloaded' }); await expect(page.locator('[data-state-id="set-new-password"]')).toBeVisible({ timeout: 20_000 }); const nextPassword = `After-${crypto.randomUUID()}-8`; await page.getByLabel('New password', { exact: true }).fill(nextPassword); await page.getByLabel('Confirm new password', { exact: true }).fill(nextPassword); await page.getByRole('button', { name: 'Set password and continue' }).click(); const id: ScenarioId = outcome === 'success' ? 'reset-update-success' : 'reset-update-error'; await expect(page.locator(`[data-state-id="${id}"]`)).toBeVisible({ timeout: 15_000 }); expect(runtime.consoleErrors).toEqual([]); expect(runtime.pageErrors).toEqual([]); expect(runtime.failedRequests).toEqual([]); record(id, { id: variant.id, viewport: `${variant.width}x${variant.height} public light`, screenshot: await screenshot(page, id, variant.id), finalUrl: new URL(page.url()).pathname, mutationReceipt: { disposableUserId: disposable.userId, email: disposable.email, recoveryLinkGeneratedLocallyWithoutEmail: true, passwordUpdatePersisted: outcome === 'success', injectedFailure: outcome === 'error' }, ...runtime });
      } finally { await deleteRecoveryUser(disposable.admin, disposable.userId); }
    });
  }

  test.afterAll(() => { for (const id of ids) { const entries = evidence.get(id) ?? []; if (!entries.length) continue; const scenario = manifest.get(id)!; const consoleErrors = entries.flatMap((entry) => entry.consoleErrors); const pageErrors = entries.flatMap((entry) => entry.pageErrors); const failedRequests = entries.flatMap((entry) => entry.failedRequests); const passed = entries.length === variants.length && !consoleErrors.length && !pageErrors.length && !failedRequests.length; fs.writeFileSync(path.join(directory(id), 'receipt.json'), `${JSON.stringify({ schemaVersion: 2, evidenceSource: 'playwright-runtime', scenarioId: id, owningSurface: scenario.owner, declaredKind: scenario.kind, activation: scenario.activationRecipe, viewport: entries.map((entry) => entry.viewport), theme: ['light'], roleProfile: { role: 'public', persona: null, delegatedPermissions: [] }, finalUrl: entries.at(-1)?.finalUrl ?? null, consoleErrors, pageErrors, failedRequests, expectedDiagnostics: entries.flatMap((entry) => entry.expectedDiagnostics), screenshotOrTrace: entries[0]?.screenshot ?? null, supportingEvidence: entries.map((entry) => entry.screenshot), mutationReceipt: entries.map((entry) => entry.mutationReceipt), cleanup: 'All auth requests stayed on loopback. Intercepted requests wrote nothing; purpose-created recovery users were deleted after each test. No email was sent.', verdict: passed ? 'passed' : entries.length ? 'partial' : 'untested', variants: entries }, null, 2)}\n`); } });
});
