import type { ReactNode } from 'react';
import Link from '@/components/navigation/AppNavLink';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { PageFrame } from '@/components/ui/PageFrame';
import { SetBreadcrumbLabel } from '@/components/layout/SetBreadcrumbLabel';
export interface DetailMetaItem { label?: string; value: ReactNode }
export interface DetailRecordNav { prevHref?: string; nextHref?: string; prevLabel?: string; nextLabel?: string }
interface Props { backHref?: string; backLabel?: string; eyebrow?: string; title: string; subtitle?: ReactNode; statusBadge?: ReactNode; meta?: DetailMetaItem[]; recordNav?: DetailRecordNav; metricStrip?: ReactNode; actions?: ReactNode; tabs?: ReactNode; children: ReactNode; rail?: ReactNode; className?: string; surfaceId?: string; archetype?: string }
export function DetailPageShell({ backHref, backLabel = 'Back', eyebrow, title, subtitle, statusBadge, meta = [], recordNav, metricStrip, actions, tabs, children, rail, className, surfaceId, archetype }: Props) { const headerActions = statusBadge || actions || recordNav ? <div className="ua-detail-actions">{statusBadge}{actions}{recordNav ? <nav className="ua-detail-recordnav" aria-label="Record navigation">{recordNav.prevHref ? <Link href={recordNav.prevHref} aria-label={recordNav.prevLabel ?? 'Previous record'}><ChevronLeft size={16} /></Link> : <span aria-disabled="true"><ChevronLeft size={16} /></span>}{recordNav.nextHref ? <Link href={recordNav.nextHref} aria-label={recordNav.nextLabel ?? 'Next record'}><ChevronRight size={16} /></Link> : <span aria-disabled="true"><ChevronRight size={16} /></span>}</nav> : null}</div> : undefined; return <div className={className}><SetBreadcrumbLabel label={title} /><PageFrame eyebrow={eyebrow} title={title} subtitle={subtitle} breadcrumbs={backHref ? [{ label: backLabel, href: backHref }, { label: title }] : undefined} showCurrentBreadcrumb meta={meta.length ? <dl className="ua-detail-meta">{meta.map((item, index) => <div key={index}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl> : undefined} actions={headerActions} tabs={tabs} metrics={metricStrip} surfaceId={surfaceId} archetype={archetype}>{rail ? <div className="ua-detail-layout"><div>{children}</div><aside>{rail}</aside></div> : children}</PageFrame></div>; }
