import type { ReactNode } from 'react';
import type { WorkbenchNavItem } from './WorkbenchNav';
import { WorkbenchKpiStrip, type WorkbenchKpiItem } from './WorkbenchKpiStrip';
import { WorkbenchActionBar } from './WorkbenchActionBar';
import { WorkbenchNav } from './WorkbenchNav';
import { PageFrame } from '@/components/ui/PageFrame';
import { Surface } from '@/components/ui/Surface';
interface Props { eyebrow?: string; title: string; subtitle?: string; navItems?: WorkbenchNavItem[]; activeNavKey?: string; actions?: ReactNode; kpiItems?: WorkbenchKpiItem[]; kpiStrip?: ReactNode; primaryVisual?: ReactNode; actionBarLeft?: ReactNode; actionBarMiddle?: ReactNode; actionBarRight?: ReactNode; actionBar?: ReactNode; main: ReactNode; mainSurface?: 'panel' | 'open'; rail?: ReactNode; footer?: ReactNode; surfaceId?: string; archetype?: string }
export function WorkbenchPage({ eyebrow, title, subtitle, navItems, activeNavKey, actions, kpiItems, kpiStrip, primaryVisual, actionBarLeft, actionBarMiddle, actionBarRight, actionBar, main, mainSurface = 'panel', rail, footer, surfaceId, archetype }: Props) { const metrics = kpiItems ? <WorkbenchKpiStrip items={kpiItems} /> : kpiStrip; const toolbar = actionBarLeft != null || actionBarMiddle != null || actionBarRight != null ? <WorkbenchActionBar left={actionBarLeft} middle={actionBarMiddle} right={actionBarRight} /> : actionBar; const mainContent = mainSurface === 'open' ? <div className="ua-workbench-main">{main}</div> : <Surface structure="working" className="ua-workbench-main">{main}</Surface>; const tabs = navItems?.length && activeNavKey ? <WorkbenchNav items={navItems} activeKey={activeNavKey} /> : undefined; return <PageFrame eyebrow={eyebrow} title={title} subtitle={subtitle} actions={actions} tabs={tabs} metrics={metrics} primaryVisual={primaryVisual} toolbar={toolbar} footer={footer} surfaceId={surfaceId} archetype={archetype}>{rail ? <div className="ua-workbench-layout">{mainContent}<aside>{rail}</aside></div> : mainContent}</PageFrame>; }
