'use client';

import { useEffect, useState } from 'react';
import { DEFAULT_PLATFORM_SETTINGS, type PlatformSettings } from '@/lib/settings/platform';

export function PlatformSettingsClient({ canManage }: { canManage: boolean }) {
  const [settings, setSettings] = useState<PlatformSettings>(DEFAULT_PLATFORM_SETTINGS); const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { fetch('/api/settings/platform').then((response) => response.json()).then((body) => body.settings && setSettings(body.settings)).catch(() => setMessage('Unable to load platform settings')); }, []);
  function patch<K extends keyof PlatformSettings>(key: K, value: PlatformSettings[K]) { setSettings((current) => ({ ...current, [key]: value })); }
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(null); const response = await fetch('/api/settings/platform', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); const body = await response.json(); setMessage(response.ok ? 'Platform settings saved.' : body.error ?? 'Unable to save settings'); }
  const number = (key: keyof PlatformSettings, label: string) => <label className="text-sm">{label}<input type="number" disabled={!canManage} value={settings[key] as number} onChange={(event) => patch(key, Number(event.target.value) as never)} className="mt-1 w-full rounded-md border p-2" /></label>;
  return <form onSubmit={save} className="space-y-6"><section className="grid gap-4 rounded-lg border bg-white p-4 md:grid-cols-2"><label className="text-sm">Reporting currency<input maxLength={3} disabled={!canManage} value={settings.reportingCurrency} onChange={(event) => patch('reportingCurrency', event.target.value.toUpperCase())} className="mt-1 w-full rounded-md border p-2" /></label><label className="text-sm">Timezone<input disabled={!canManage} value={settings.timezone} onChange={(event) => patch('timezone', event.target.value)} className="mt-1 w-full rounded-md border p-2" /></label>{number('retentionDays','Retention days')}{number('defaultDateRangeDays','Default date range (days)')}</section><section className="grid gap-4 rounded-lg border bg-white p-4 md:grid-cols-2"><label className="text-sm">Matching policy<select disabled={!canManage} value={settings.matchingPolicy} onChange={(event) => patch('matchingPolicy', event.target.value as PlatformSettings['matchingPolicy'])} className="mt-1 w-full rounded-md border p-2"><option value="strict">Strict</option><option value="balanced">Balanced</option><option value="review_ambiguous">Review ambiguous</option></select></label><label className="text-sm">Cost basis<select disabled={!canManage} value={settings.costBasis} onChange={(event) => patch('costBasis', event.target.value as PlatformSettings['costBasis'])} className="mt-1 w-full rounded-md border p-2"><option value="actual">Actual</option><option value="average">Average</option><option value="standard">Standard</option></select></label>{number('defaultDeadlineHours','Default deadline (hours)')}{number('approvalLimitMinor','Approval limit (minor units)')}{number('escalationThresholdMinor','Escalation threshold (minor units)')}{number('syncFrequencyMinutes','Sync frequency (minutes)')}</section><section className="space-y-3 rounded-lg border bg-white p-4"><label className="flex gap-2 text-sm"><input type="checkbox" disabled={!canManage} checked={settings.connectorWritebackEnabled} onChange={(event) => patch('connectorWritebackEnabled', event.target.checked)} />Allow controlled connector write-back</label><label className="flex gap-2 text-sm"><input type="checkbox" disabled={!canManage} checked={settings.webhookHealthAlerts} onChange={(event) => patch('webhookHealthAlerts', event.target.checked)} />Alert on webhook health failures</label></section>{canManage ? <button type="submit" className="rounded-md px-4 py-2 text-sm font-medium" style={{ background: 'var(--accent)', color: 'white' }}>Save platform settings</button> : null}{message ? <p role="status" className="text-sm">{message}</p> : null}</form>;
}
