-- Restore the canonical role privileges after the linked-schema reconciliation.
-- This migration is idempotent and intentionally contains no data mutation.
SET check_function_bodies = false;
COMMENT ON SCHEMA public IS 'standard public schema';
ALTER SCHEMA public OWNER TO pg_database_owner;
REVOKE CREATE ON SCHEMA public FROM postgres;
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON ROUTINES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT UPDATE ON SEQUENCES TO service_role;
GRANT UPDATE ON SEQUENCE public.evidence_package_daily_seq TO anon;
GRANT UPDATE ON SEQUENCE public.evidence_package_daily_seq TO authenticated;
GRANT ALL ON SEQUENCE public.evidence_package_daily_seq TO service_role;
GRANT UPDATE ON SEQUENCE public.migration_orphans_id_seq TO anon;
GRANT UPDATE ON SEQUENCE public.migration_orphans_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.migration_orphans_id_seq TO service_role;
GRANT ALL ON FUNCTION public._distinctive_analytics_assert_scope(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public._distinctive_analytics_envelope(jsonb, timestamp with time zone, timestamp with time zone, text, jsonb, bigint, text[]) TO service_role;
GRANT ALL ON FUNCTION public.add_merchant_topup_credits(uuid, integer, numeric, text) TO service_role;
GRANT ALL ON FUNCTION public.all_processing_job_chunks_complete(uuid) TO service_role;
GRANT ALL ON FUNCTION public.archive_merchant_rule(uuid, uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.audit_claim_status_change() TO service_role;
GRANT ALL ON FUNCTION public.audit_safe_uuid(text) TO service_role;
GRANT ALL ON FUNCTION public.begin_processing_job_chunk(uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.bulk_transition_work_tasks(uuid, uuid, uuid[], text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.capture_sensitive_audit_event() IS 'Atomically appends a durable audit domain event for an inventoried sensitive mutation; failure aborts the mutation.';
GRANT ALL ON FUNCTION public.capture_sensitive_audit_event() TO service_role;
COMMENT ON FUNCTION public.claim_case_investigation_dispatch(uuid,uuid,text,text,text,text,uuid,integer) IS 'Claims a durable investigation email attempt without allowing concurrent duplicate sends.';
GRANT ALL ON FUNCTION public.claim_case_investigation_dispatch(uuid, uuid, text, text, text, text, uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.claim_domain_event_deliveries(text, integer, text, integer) TO service_role;
GRANT ALL ON FUNCTION public.claim_ingestion_event(uuid, text, integer) TO service_role;
GRANT ALL ON FUNCTION public.claim_privacy_storage_cleanup_jobs(integer, text, integer, uuid) TO service_role;
GRANT ALL ON FUNCTION public.claim_processed_webhook(text, text, text, text, text, integer, text, bigint) TO service_role;
GRANT ALL ON FUNCTION public.claim_sync_job(integer, text, integer) TO service_role;
COMMENT ON FUNCTION public.complete_case_investigation_dispatch(uuid,uuid,uuid,boolean,text,text) IS 'Reconciles provider acceptance or failure against the active dispatch lease.';
GRANT ALL ON FUNCTION public.complete_case_investigation_dispatch(uuid, uuid, uuid, boolean, text, text) TO service_role;
GRANT ALL ON FUNCTION public.complete_domain_event_delivery(uuid) TO service_role;
GRANT ALL ON FUNCTION public.complete_privacy_storage_cleanup_job(uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.complete_processed_webhook(text, uuid, text, text, jsonb) TO service_role;
GRANT ALL ON FUNCTION public.complete_processing_job_chunk(uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.consume_context_credits_if_available(uuid, uuid, text, text, integer, timestamp with time zone, timestamp with time zone, integer, uuid, text, text, text, text, jsonb, boolean) TO service_role;
COMMENT ON FUNCTION public.correct_case_issue(uuid,uuid,bigint,text,text,uuid,text) IS 'Corrects the authoritative normalized case issue with optimistic concurrency and immutable audit evidence.';
GRANT ALL ON FUNCTION public.correct_case_issue(uuid, uuid, bigint, text, text, uuid, text) TO service_role;
COMMENT ON FUNCTION public.create_case_investigation(uuid,uuid,text,text,uuid,text,text,text,text[],text,text,text,text,text,timestamp with time zone,boolean,uuid,text) IS 'Creates one merchant-scoped, idempotent investigation draft and semantic domain event.';
GRANT ALL ON FUNCTION public.create_case_investigation(uuid, uuid, text, text, uuid, text, text, text, text[], text, text, text, text, text, timestamp with time zone, boolean, uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.create_merchant_rule_draft_pack(uuid, uuid, jsonb) TO service_role;
GRANT ALL ON FUNCTION public.create_merchant_rule_draft(uuid, uuid, text, text, jsonb, text, text, integer) TO service_role;
GRANT ALL ON FUNCTION public.deduct_merchant_credits(uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.discard_merchant_rule_draft(uuid, uuid, uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.enforce_recovery_case_integrity() TO service_role;
GRANT ALL ON FUNCTION public.erase_merchant_data_subject(uuid, uuid, uuid, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.erase_release1_merchant_data_subject(uuid,uuid,uuid,text,timestamp with time zone) IS 'Atomically erases the canonical subject scope and Release 1 investigation content, with durable Storage cleanup jobs.';
GRANT ALL ON FUNCTION public.erase_release1_merchant_data_subject(uuid, uuid, uuid, text, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.fail_domain_event_delivery(uuid, text, integer) TO service_role;
GRANT ALL ON FUNCTION public.fail_privacy_storage_cleanup_job(uuid, text, text) TO service_role;
GRANT ALL ON FUNCTION public.fail_processing_job_chunk(uuid, integer, text) TO service_role;
GRANT ALL ON FUNCTION public.finalize_due_prevention_observations(integer, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.flag_aged_payout_case(uuid, uuid, timestamp with time zone, text) TO service_role;
GRANT ALL ON FUNCTION public.forbid_account_deletion_receipt_mutation() TO service_role;
GRANT ALL ON FUNCTION public.forbid_domain_event_mutation() TO service_role;
GRANT ALL ON FUNCTION public.forbid_financial_entry_mutation() TO service_role;
GRANT ALL ON FUNCTION public.forbid_mutation() TO service_role;
GRANT ALL ON FUNCTION public.forbid_phase7_history_mutation() TO service_role;
GRANT ALL ON FUNCTION public.forbid_user_action_log_mutation() TO service_role;
GRANT ALL ON FUNCTION public.generate_evidence_reference() TO service_role;
COMMENT ON FUNCTION public.get_automation_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only rule evaluation and workflow run analytics.';
GRANT ALL ON FUNCTION public.get_automation_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.get_evidence_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only recommendation snapshot readiness and evidence-gap analytics.';
GRANT ALL ON FUNCTION public.get_evidence_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.get_financial_analytics_records(uuid,uuid,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone,integer,integer) IS 'Exact immutable-entry drill-down for a financial analytics chart cell.';
GRANT ALL ON FUNCTION public.get_financial_analytics_records(uuid, uuid, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone, integer, integer) TO service_role;
COMMENT ON FUNCTION public.get_financial_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only, merchant-scoped immutable financial analytics with currency separation and provenance.';
GRANT ALL ON FUNCTION public.get_financial_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.get_financial_report_records(uuid,timestamp with time zone,text,text,text,integer,integer) IS 'Merchant-scoped canonical financial drill-down; normalized case issue controls category routing.';
GRANT ALL ON FUNCTION public.get_financial_report_records(uuid, timestamp with time zone, text, text, text, integer, integer) TO service_role;
COMMENT ON FUNCTION public.get_recovery_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only recovery event and immutable value analytics.';
GRANT ALL ON FUNCTION public.get_recovery_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.get_source_health_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only ingestion and current source-watermark analytics.';
GRANT ALL ON FUNCTION public.get_source_health_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.get_work_analytics(uuid,uuid,text,timestamp with time zone,timestamp with time zone,text,text,text,timestamp with time zone) IS 'Service-role-only task stock/flow analytics; never reconstructs historical task state from updated_at.';
GRANT ALL ON FUNCTION public.get_work_analytics(uuid, uuid, text, timestamp with time zone, timestamp with time zone, text, text, text, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.increment_api_key_minute_count(uuid, bigint) TO service_role;
GRANT ALL ON FUNCTION public.increment_job_progress(uuid, integer, integer) TO service_role;
GRANT ALL ON FUNCTION public.increment_rate_limit(text, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.ingest_identity_observations(uuid, jsonb, jsonb) TO service_role;
GRANT ALL ON FUNCTION public.is_merchant_member(uuid) TO authenticated;
GRANT ALL ON FUNCTION public.is_merchant_member(uuid) TO service_role;
GRANT ALL ON FUNCTION public.lookup_network_identity(uuid, jsonb, inet) TO service_role;
GRANT ALL ON FUNCTION public.merchant_role(uuid) TO authenticated;
GRANT ALL ON FUNCTION public.merchant_role(uuid) TO service_role;
GRANT ALL ON FUNCTION public.next_pending_processing_chunk_index(uuid) TO service_role;
GRANT ALL ON FUNCTION public.protect_published_rule_version_payload() TO service_role;
GRANT ALL ON FUNCTION public.protect_published_workflow_payload() TO service_role;
GRANT ALL ON FUNCTION public.publish_merchant_rule_version(uuid, uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.publish_workflow_definition(uuid, uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.purge_expired_ingestion_payloads(integer) TO service_role;
GRANT ALL ON FUNCTION public.purge_merchant_audit_projection(uuid) TO service_role;
GRANT ALL ON FUNCTION public.purge_merchant_privacy_records(uuid) TO service_role;
GRANT ALL ON FUNCTION public.purge_merchant_reconciliation_history(uuid) TO service_role;
GRANT ALL ON FUNCTION public.purge_merchant_source_agnostic(uuid) TO service_role;
GRANT ALL ON FUNCTION public.recompute_case_financial_summary(uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.record_account_deletion_receipt(uuid, uuid, text, uuid, text, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.record_case_decision(uuid, uuid, bigint, text, text, bigint, text, text, uuid, jsonb, boolean, jsonb, text, boolean) TO service_role;
COMMENT ON FUNCTION public.record_case_responsibility(uuid,uuid,bigint,text,text,text,text,uuid[],uuid[],text,uuid,text) IS 'Atomically confirms or corrects merchant responsibility with scoped evidence, concurrency, idempotency, and immutable audit.';
GRANT ALL ON FUNCTION public.record_case_responsibility(uuid, uuid, bigint, text, text, text, text, uuid[], uuid[], text, uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.record_case_source_outcome(uuid, uuid, text, text, bigint, bigint, text, text, uuid, jsonb, timestamp with time zone, text) TO service_role;
GRANT ALL ON FUNCTION public.record_domain_event(uuid, text, text, uuid, text, jsonb, uuid, uuid, uuid, text, uuid, timestamp with time zone, uuid, uuid, text[]) TO service_role;
GRANT ALL ON FUNCTION public.record_recovery_claim_pack(uuid, uuid, uuid, uuid, text, text, text, jsonb, jsonb, text, text, text, text, uuid, text, uuid) TO service_role;
GRANT ALL ON FUNCTION public.record_recovery_claim_submission(uuid, uuid, uuid, text, text, text, text, bigint, text, timestamp with time zone, uuid, uuid, uuid, text, text) TO service_role;
GRANT ALL ON FUNCTION public.record_recovery_provider_response(uuid, uuid, uuid, text, text, text, bigint, bigint, bigint, text, text, text, uuid, uuid, timestamp with time zone, uuid, text, text) TO service_role;
GRANT ALL ON FUNCTION public.refresh_audit_customer_summaries(uuid, uuid) TO service_role;
GRANT ALL ON FUNCTION public.register_processing_job_chunks(uuid, uuid, integer, text, jsonb) TO service_role;
GRANT ALL ON FUNCTION public.reorder_merchant_rules(uuid, uuid, jsonb) TO service_role;
GRANT ALL ON FUNCTION public.reset_merchant_monthly_credits(uuid, integer, timestamp with time zone) TO service_role;
COMMENT ON FUNCTION public.revoke_merchant_api_key(uuid,uuid,timestamp with time zone) IS 'Atomically revokes a merchant API key and all paired widget tokens. Service role only.';
GRANT ALL ON FUNCTION public.revoke_merchant_api_key(uuid, uuid, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.set_checkout_signal_cross_merchant_hits(uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.set_merchant_monthly_credits(uuid, integer) TO service_role;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;
GRANT ALL ON FUNCTION public.settle_case_exception_v1(uuid, uuid, text, text, uuid, bigint) TO service_role;
GRANT ALL ON FUNCTION public.transfer_merchant_ownership(uuid, uuid, uuid, text) TO service_role;
COMMENT ON FUNCTION public.transition_case_investigation(uuid,uuid,uuid,bigint,text,jsonb,uuid,text) IS 'Atomically transitions an investigation, Work tasks, primary selection, case status, and audit events.';
GRANT ALL ON FUNCTION public.transition_case_investigation(uuid, uuid, uuid, bigint, text, jsonb, uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.transition_payout_case(uuid, uuid, bigint, jsonb, text, uuid, text, text, jsonb, text[], text, jsonb, text, boolean, boolean, boolean, boolean) TO service_role;
GRANT ALL ON FUNCTION public.transition_recovery_case(uuid, uuid, public.recovery_case_status, public.recovery_case_event_type, text, bigint, uuid, text) TO service_role;
GRANT ALL ON FUNCTION public.try_claim_job_finalize(uuid) TO service_role;
GRANT ALL ON FUNCTION public.work_view_counts(uuid, uuid, timestamp with time zone) TO service_role;
GRANT ALL ON FUNCTION public.write_off_loss_case(uuid, uuid, text, uuid, text) TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.access_audit_log TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.access_audit_log TO authenticated;
GRANT ALL ON public.access_audit_log TO service_role;
GRANT ALL ON public.account_deletion_audit_receipts TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.accountability_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.accountability_events TO authenticated;
GRANT ALL ON public.accountability_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.agreement_clauses TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.agreement_clauses TO authenticated;
GRANT ALL ON public.agreement_clauses TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.agreement_rule_evaluations TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.agreement_rule_evaluations TO authenticated;
GRANT ALL ON public.agreement_rule_evaluations TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.agreement_rules TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.agreement_rules TO authenticated;
GRANT ALL ON public.agreement_rules TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.agreements TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.agreements TO authenticated;
GRANT ALL ON public.agreements TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.api_key_minute_counts TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.api_key_minute_counts TO authenticated;
GRANT ALL ON public.api_key_minute_counts TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.audit_customer_summaries TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.audit_customer_summaries TO authenticated;
GRANT ALL ON public.audit_customer_summaries TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.audit_result_summaries TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.audit_result_summaries TO authenticated;
GRANT ALL ON public.audit_result_summaries TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.billing_events_log TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.billing_events_log TO authenticated;
GRANT ALL ON public.billing_events_log TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_claimed_items TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_claimed_items TO authenticated;
GRANT ALL ON public.case_claimed_items TO service_role;
COMMENT ON TABLE public.case_clarification_requests IS 'Case investigation read model. Transport and provider response facts remain explicit.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_clarification_requests TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_clarification_requests TO authenticated;
GRANT ALL ON public.case_clarification_requests TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_comment_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_comment_events TO authenticated;
GRANT ALL ON public.case_comment_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_comments TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_comments TO authenticated;
GRANT ALL ON public.case_comments TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_decisions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_decisions TO authenticated;
GRANT ALL ON public.case_decisions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_exceptions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_exceptions TO authenticated;
GRANT ALL ON public.case_exceptions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_financial_entries TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_financial_entries TO authenticated;
GRANT ALL ON public.case_financial_entries TO service_role;
COMMENT ON COLUMN public.case_financial_summaries.known_states IS 'States backed by at least one ledger entry. A numeric zero outside this set is unknown, not a proven zero.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_financial_summaries TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_financial_summaries TO authenticated;
GRANT ALL ON public.case_financial_summaries TO service_role;
COMMENT ON TABLE public.case_investigation_attachments IS 'Private response files and validated links. Files remain unusable evidence until safety_status is clean.';
GRANT SELECT ON public.case_investigation_attachments TO authenticated;
GRANT ALL ON public.case_investigation_attachments TO service_role;
COMMENT ON TABLE public.case_investigation_dispatches IS 'Durable idempotent transport attempts for case investigation requests and chases.';
GRANT SELECT ON public.case_investigation_dispatches TO authenticated;
GRANT ALL ON public.case_investigation_dispatches TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_outcome_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_outcome_events TO authenticated;
GRANT ALL ON public.case_outcome_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_outcomes TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_outcomes TO authenticated;
GRANT ALL ON public.case_outcomes TO service_role;
COMMENT ON TABLE public.case_prevention_observations IS 'Matured prevented-value observations. Missing observations are unavailable, never inferred as zero.';
GRANT MAINTAIN ON public.case_prevention_observations TO anon;
GRANT MAINTAIN, SELECT ON public.case_prevention_observations TO authenticated;
GRANT ALL ON public.case_prevention_observations TO service_role;
COMMENT ON TABLE public.case_recommendation_snapshots IS 'Append-only independent customer-action, responsibility, and recovery recommendations.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.case_recommendation_snapshots TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.case_recommendation_snapshots TO authenticated;
GRANT ALL ON public.case_recommendation_snapshots TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.category_applicability TO anon;
GRANT ALL ON public.category_applicability TO authenticated;
GRANT ALL ON public.category_applicability TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.checkout_signal_order_links TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.checkout_signal_order_links TO authenticated;
GRANT ALL ON public.checkout_signal_order_links TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.checkout_signals TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.checkout_signals TO authenticated;
GRANT ALL ON public.checkout_signals TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.claim_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.claim_events TO authenticated;
GRANT ALL ON public.claim_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.claim_evidence TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.claim_evidence TO authenticated;
GRANT ALL ON public.claim_evidence TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.claim_outcomes TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.claim_outcomes TO authenticated;
GRANT ALL ON public.claim_outcomes TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.comment_mentions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.comment_mentions TO authenticated;
GRANT ALL ON public.comment_mentions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.connector_action_runs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.connector_action_runs TO authenticated;
GRANT ALL ON public.connector_action_runs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.context_credit_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.context_credit_events TO authenticated;
GRANT ALL ON public.context_credit_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.correspondence_automation_settings TO anon;
GRANT ALL ON public.correspondence_automation_settings TO authenticated;
GRANT ALL ON public.correspondence_automation_settings TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.credit_topup_log TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.credit_topup_log TO authenticated;
GRANT ALL ON public.credit_topup_log TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.customer_claim_summary TO anon;
GRANT ALL ON public.customer_claim_summary TO authenticated;
GRANT ALL ON public.customer_claim_summary TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.customer_identity_signals TO anon;
GRANT ALL ON public.customer_identity_signals TO authenticated;
GRANT ALL ON public.customer_identity_signals TO service_role;
GRANT ALL ON public.data_subject_erasure_receipts TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.default_rule_templates TO anon;
GRANT ALL ON public.default_rule_templates TO authenticated;
GRANT ALL ON public.default_rule_templates TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.document_upload_jobs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.document_upload_jobs TO authenticated;
GRANT ALL ON public.document_upload_jobs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.domain_event_deliveries TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.domain_event_deliveries TO authenticated;
GRANT ALL ON public.domain_event_deliveries TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.domain_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.domain_events TO authenticated;
GRANT ALL ON public.domain_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.entity_relationships TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.entity_relationships TO authenticated;
GRANT ALL ON public.entity_relationships TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.evidence_download_tokens TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.evidence_download_tokens TO authenticated;
GRANT ALL ON public.evidence_download_tokens TO service_role;
COMMENT ON COLUMN public.evidence_items.fact_kind IS 'Whether the evidence is a source fact, human finding, or derived inference.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.evidence_items TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.evidence_items TO authenticated;
GRANT ALL ON public.evidence_items TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.evidence_links TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.evidence_links TO authenticated;
GRANT ALL ON public.evidence_links TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.evidence_packages TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.evidence_packages TO authenticated;
GRANT ALL ON public.evidence_packages TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.external_clarification_requests TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.external_clarification_requests TO authenticated;
GRANT ALL ON public.external_clarification_requests TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.external_correspondence TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.external_correspondence TO authenticated;
GRANT ALL ON public.external_correspondence TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.extracted_partner_terms TO anon;
GRANT ALL ON public.extracted_partner_terms TO authenticated;
GRANT ALL ON public.extracted_partner_terms TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.founding_merchant_applications TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.founding_merchant_applications TO authenticated;
GRANT ALL ON public.founding_merchant_applications TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.helpdesk_connections TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.helpdesk_connections TO authenticated;
GRANT ALL ON public.helpdesk_connections TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identities TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identities TO authenticated;
GRANT ALL ON public.identities TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_catch_events TO anon;
GRANT ALL ON public.identity_catch_events TO authenticated;
GRANT ALL ON public.identity_catch_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_edges TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_edges TO authenticated;
GRANT ALL ON public.identity_edges TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_evidence_scores TO anon;
GRANT ALL ON public.identity_evidence_scores TO authenticated;
GRANT ALL ON public.identity_evidence_scores TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_link_candidates TO anon;
GRANT ALL ON public.identity_link_candidates TO authenticated;
GRANT ALL ON public.identity_link_candidates TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_members TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_members TO authenticated;
GRANT ALL ON public.identity_members TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_notes TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.identity_notes TO authenticated;
GRANT ALL ON public.identity_notes TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_profiles TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_profiles TO authenticated;
GRANT ALL ON public.identity_profiles TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_resolution_events TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_resolution_events TO authenticated;
GRANT ALL ON public.identity_resolution_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_signals TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.identity_signals TO authenticated;
GRANT ALL ON public.identity_signals TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ingest_rate_limits TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ingest_rate_limits TO authenticated;
GRANT ALL ON public.ingest_rate_limits TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ingestion_events TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ingestion_events TO authenticated;
GRANT ALL ON public.ingestion_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.ingestion_field_errors TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.ingestion_field_errors TO authenticated;
GRANT ALL ON public.ingestion_field_errors TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.integration_credentials TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.integration_credentials TO authenticated;
GRANT ALL ON public.integration_credentials TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.integration_documents TO anon;
GRANT ALL ON public.integration_documents TO authenticated;
GRANT ALL ON public.integration_documents TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.integration_evidence_items TO anon;
GRANT ALL ON public.integration_evidence_items TO authenticated;
GRANT ALL ON public.integration_evidence_items TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.loss_attribution_candidates TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.loss_attribution_candidates TO authenticated;
GRANT ALL ON public.loss_attribution_candidates TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.loss_case_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.loss_case_events TO authenticated;
GRANT ALL ON public.loss_case_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.loss_case_evidence TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.loss_case_evidence TO authenticated;
GRANT ALL ON public.loss_case_evidence TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.loss_cases TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.loss_cases TO authenticated;
GRANT ALL ON public.loss_cases TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.loss_sources TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.loss_sources TO authenticated;
GRANT ALL ON public.loss_sources TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_api_keys TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_api_keys TO authenticated;
GRANT ALL ON public.merchant_api_keys TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_credits TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_credits TO authenticated;
GRANT ALL ON public.merchant_credits TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_customer_signals TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_customer_signals TO authenticated;
GRANT ALL ON public.merchant_customer_signals TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_customers TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_customers TO authenticated;
GRANT ALL ON public.merchant_customers TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_identity_state TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_identity_state TO authenticated;
GRANT ALL ON public.merchant_identity_state TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_integrations TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_integrations TO authenticated;
GRANT ALL ON public.merchant_integrations TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_rule_versions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_rule_versions TO authenticated;
GRANT ALL ON public.merchant_rule_versions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_rules TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_rules TO authenticated;
GRANT ALL ON public.merchant_rules TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_subscriptions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_subscriptions TO authenticated;
GRANT ALL ON public.merchant_subscriptions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_users TO anon;
GRANT ALL ON public.merchant_users TO authenticated;
GRANT ALL ON public.merchant_users TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchant_widget_tokens TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.merchant_widget_tokens TO authenticated;
GRANT ALL ON public.merchant_widget_tokens TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.merchants TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.merchants TO authenticated;
GRANT ALL ON public.merchants TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.migration_orphans TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.migration_orphans TO authenticated;
GRANT ALL ON public.migration_orphans TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.network_access_log TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.network_access_log TO authenticated;
GRANT ALL ON public.network_access_log TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.notification_preferences TO anon;
GRANT ALL ON public.notification_preferences TO authenticated;
GRANT ALL ON public.notification_preferences TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.notifications TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.notifications TO authenticated;
GRANT ALL ON public.notifications TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.oauth_connection_transactions TO anon;
GRANT ALL ON public.oauth_connection_transactions TO authenticated;
GRANT ALL ON public.oauth_connection_transactions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.order_claim_context TO anon;
GRANT ALL ON public.order_claim_context TO authenticated;
GRANT ALL ON public.order_claim_context TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pack_confirmations TO anon;
GRANT ALL ON public.pack_confirmations TO authenticated;
GRANT ALL ON public.pack_confirmations TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.partner_recovery_rules TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.partner_recovery_rules TO authenticated;
GRANT ALL ON public.partner_recovery_rules TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.partners TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.partners TO authenticated;
GRANT ALL ON public.partners TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.pending_provider_account_selections TO anon;
GRANT ALL ON public.pending_provider_account_selections TO authenticated;
GRANT ALL ON public.pending_provider_account_selections TO service_role;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.plans TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.plans TO authenticated;
GRANT ALL ON public.plans TO service_role;
GRANT ALL ON public.privacy_storage_cleanup_jobs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.processed_webhooks TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.processed_webhooks TO authenticated;
GRANT ALL ON public.processed_webhooks TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_view_tokens TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.profile_view_tokens TO authenticated;
GRANT ALL ON public.profile_view_tokens TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.provider_credit_records TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.provider_credit_records TO authenticated;
GRANT ALL ON public.provider_credit_records TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.record_match_candidates TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.record_match_candidates TO authenticated;
GRANT ALL ON public.record_match_candidates TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.record_match_resolutions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.record_match_resolutions TO authenticated;
GRANT ALL ON public.record_match_resolutions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_case_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_case_events TO authenticated;
GRANT ALL ON public.recovery_case_events TO service_role;
COMMENT ON COLUMN public.recovery_cases.provider_claim_stage IS 'Settlement truth: approval is not credit, and credit is not reconciled recovery.';
COMMENT ON COLUMN public.recovery_cases.last_source_event_at IS 'Timestamp of the newest underlying provider/source event used by this recovery. Independent of internal row updates.';
COMMENT ON COLUMN public.recovery_cases.provider_position IS 'Provider liability position, separate from merchant responsibility recommendation and recovery stage.';
COMMENT ON COLUMN public.recovery_cases.amount_sought_minor IS 'Authoritative recovery amount sought in integer minor units; legacy numeric major-unit columns are compatibility projections.';
COMMENT ON COLUMN public.recovery_cases.amount_approved_minor IS 'Provider approval amount. Approval is not recovered cash.';
COMMENT ON COLUMN public.recovery_cases.amount_recovered_minor IS 'Cumulative value actually received or credited back, in integer minor units.';
COMMENT ON COLUMN public.recovery_cases.amount_written_off_minor IS 'Cumulative pursued value explicitly closed without recovery, in integer minor units.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_cases TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_cases TO authenticated;
GRANT ALL ON public.recovery_cases TO service_role;
COMMENT ON TABLE public.recovery_claim_packs IS 'Immutable provider claim-pack versions. A final pack is only a frozen manifest of merchant-approved source evidence.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_claim_packs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_claim_packs TO authenticated;
GRANT ALL ON public.recovery_claim_packs TO service_role;
COMMENT ON TABLE public.recovery_claim_submissions IS 'Append-only manual external submission receipts. Unauth never sends a provider claim.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_claim_submissions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_claim_submissions TO authenticated;
GRANT ALL ON public.recovery_claim_submissions TO service_role;
COMMENT ON TABLE public.recovery_provider_responses IS 'Append-only provider positions and compensation records; approval, credit, and reconciliation remain separate.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_provider_responses TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_provider_responses TO authenticated;
GRANT ALL ON public.recovery_provider_responses TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.recovery_tasks TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.recovery_tasks TO authenticated;
GRANT ALL ON public.recovery_tasks TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.rule_evaluations TO anon;
GRANT ALL ON public.rule_evaluations TO authenticated;
GRANT ALL ON public.rule_evaluations TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_accounts TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_accounts TO authenticated;
GRANT ALL ON public.source_accounts TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_addresses TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_addresses TO authenticated;
GRANT ALL ON public.source_addresses TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_customers TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_customers TO authenticated;
GRANT ALL ON public.source_customers TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_disputes TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_disputes TO authenticated;
GRANT ALL ON public.source_disputes TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_fulfillments TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_fulfillments TO authenticated;
GRANT ALL ON public.source_fulfillments TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_locations TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_locations TO authenticated;
GRANT ALL ON public.source_locations TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_messages TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_messages TO authenticated;
GRANT ALL ON public.source_messages TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_order_lines TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_order_lines TO authenticated;
GRANT ALL ON public.source_order_lines TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_orders TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_orders TO authenticated;
GRANT ALL ON public.source_orders TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_payments TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_payments TO authenticated;
GRANT ALL ON public.source_payments TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_records TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_records TO authenticated;
GRANT ALL ON public.source_records TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_refunds TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_refunds TO authenticated;
GRANT ALL ON public.source_refunds TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_replacements TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_replacements TO authenticated;
GRANT ALL ON public.source_replacements TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_returns TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_returns TO authenticated;
GRANT ALL ON public.source_returns TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_shipment_lines TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_shipment_lines TO authenticated;
GRANT ALL ON public.source_shipment_lines TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_shipments TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_shipments TO authenticated;
GRANT ALL ON public.source_shipments TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_ticket_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_ticket_events TO authenticated;
GRANT ALL ON public.source_ticket_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_tickets TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_tickets TO authenticated;
GRANT ALL ON public.source_tickets TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_tracking_events TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_tracking_events TO authenticated;
GRANT ALL ON public.source_tracking_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.source_transactions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.source_transactions TO authenticated;
GRANT ALL ON public.source_transactions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.store_connections TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.store_connections TO authenticated;
GRANT ALL ON public.store_connections TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.support_case_events TO anon;
GRANT ALL ON public.support_case_events TO authenticated;
GRANT ALL ON public.support_case_events TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.support_case_intake TO anon;
GRANT ALL ON public.support_case_intake TO authenticated;
GRANT ALL ON public.support_case_intake TO service_role;
COMMENT ON COLUMN public.support_payout_cases.responsibility_confirmation_state IS 'Merchant-owned responsibility confirmation state. Automated evaluation may not overwrite confirmed or corrected responsibility.';
COMMENT ON COLUMN public.support_payout_cases.responsibility_event_id IS 'Immutable domain event that records the current merchant responsibility confirmation.';
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.support_payout_cases TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.support_payout_cases TO authenticated;
GRANT ALL ON public.support_payout_cases TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.support_provider_connections TO anon;
GRANT ALL ON public.support_provider_connections TO authenticated;
GRANT ALL ON public.support_provider_connections TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sync_job_chunks TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sync_job_chunks TO authenticated;
GRANT ALL ON public.sync_job_chunks TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.sync_jobs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.sync_jobs TO authenticated;
GRANT ALL ON public.sync_jobs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.unmatched_correspondence TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.unmatched_correspondence TO authenticated;
GRANT ALL ON public.unmatched_correspondence TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.user_action_log TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.user_action_log TO authenticated;
GRANT ALL ON public.user_action_log TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.user_permission_grants TO anon;
GRANT ALL ON public.user_permission_grants TO authenticated;
GRANT ALL ON public.user_permission_grants TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.webhook_logs TO anon;
GRANT ALL ON public.webhook_logs TO authenticated;
GRANT ALL ON public.webhook_logs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.work_saved_views TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.work_saved_views TO authenticated;
GRANT ALL ON public.work_saved_views TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.work_tasks TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.work_tasks TO authenticated;
GRANT ALL ON public.work_tasks TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.workflow_definitions TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.workflow_definitions TO authenticated;
GRANT ALL ON public.workflow_definitions TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.workflow_runs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.workflow_runs TO authenticated;
GRANT ALL ON public.workflow_runs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.workflow_step_runs TO anon;
GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE ON public.workflow_step_runs TO authenticated;
GRANT ALL ON public.workflow_step_runs TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.commerce_store_connections TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.commerce_store_connections TO authenticated;
GRANT ALL ON public.commerce_store_connections TO service_role;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.reporting_case_dimensions TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.reporting_case_dimensions TO authenticated;
GRANT ALL ON public.reporting_case_dimensions TO service_role;
