import { TABLES } from '@/lib/supabase/tables';
import { normaliseCurrencyOrNull } from '@/lib/canonical/money';

export const REPORT_RANGES = ['7d', '30d', '90d', 'all'] as const;
export type ReportRange = (typeof REPORT_RANGES)[number];
export type MoneyBridge = { currency:string; requestedMinor:number; paidMinor:number; preventedMinor:number; realisedLossMinor:number; recoverableMinor:number; recoveredMinor:number; outstandingMinor:number; writtenOffMinor:number; caseIds:string[] };
export type RankedRow = { key:string; label:string; count:number; amountMinor:number; currency:string; href:string };
export type CoverageRow = { objectType:string; records:number; freshRecords:number; staleRecords:number; latestAt:string|null; href:string };
export type IntelligenceReport = { range:ReportRange; timezone:string; generatedAt:string; bridges:MoneyBridge[]; causes:RankedRow[]; operations:Array<{key:string;label:string;count:number;href:string}>; recoveries:RankedRow[]; coverage:CoverageRow[]; reconciliation:{ok:boolean;issues:string[]}; recordCount:number };

type Client={from:(table:string)=>any};
const RANGE_DAYS:Record<Exclude<ReportRange,'all'>,number>={ '7d':7,'30d':30,'90d':90 };
export function parseReportRange(value:string|undefined):ReportRange{return REPORT_RANGES.includes(value as ReportRange)?value as ReportRange:'30d'}
export function reportCutoff(range:ReportRange, now=new Date()):string|null { if(range==='all')return null; return new Date(now.getTime()-RANGE_DAYS[range]*86400000).toISOString(); }
export function aggregateMoneyBridges(rows:Array<Record<string,any>>):MoneyBridge[]{const byCurrency=new Map<string,MoneyBridge>();for(const row of rows){const currency=normaliseCurrencyOrNull(row.currency);if(!currency)continue;const b=byCurrency.get(currency)??{currency,requestedMinor:0,paidMinor:0,preventedMinor:0,realisedLossMinor:0,recoverableMinor:0,recoveredMinor:0,outstandingMinor:0,writtenOffMinor:0,caseIds:[]};b.requestedMinor+=Number(row.requested_minor||0);b.paidMinor+=Number(row.paid_minor||0);b.preventedMinor+=Number(row.prevented_minor||0);b.realisedLossMinor+=Number(row.confirmed_loss_minor||0);b.recoverableMinor+=Number(row.recoverable_minor||0);b.recoveredMinor+=Number(row.recovered_minor||0);b.writtenOffMinor+=Number(row.written_off_minor||0);b.caseIds.push(row.support_payout_case_id);byCurrency.set(currency,b)}for(const b of byCurrency.values())b.outstandingMinor=Math.max(0,b.recoverableMinor-b.recoveredMinor-b.writtenOffMinor);return[...byCurrency.values()].sort((a,b)=>a.currency.localeCompare(b.currency))}

function addRank(map:Map<string,RankedRow>, key:string, label:string, amountMinor:number, currency:string, href:string){const id=`${key}:${currency}`;const row=map.get(id)??{key,label,count:0,amountMinor:0,currency,href};row.count++;row.amountMinor+=amountMinor;map.set(id,row)}

/** Canonical reporting projection. Money never crosses currency boundaries. */
export async function loadIntelligenceReport(client:Client,merchantId:string,range:ReportRange,timezone='UTC'):Promise<IntelligenceReport>{
  const cutoff=reportCutoff(range);
  let casesQuery=client.from(TABLES.MERCHANT_CLAIMS).select('id,status,claim_type,reason_normalized,loss_attribution,currency,submitted_at,created_at,updated_at').eq('merchant_id',merchantId).order('updated_at',{ascending:false}).limit(10000);
  if(cutoff)casesQuery=casesQuery.gte('submitted_at',cutoff);
  const {data:caseData}=await casesQuery; const cases=(caseData??[]) as Array<Record<string,any>>; const caseIds=cases.map(c=>c.id);
  const {data:financialData}=caseIds.length?await client.from(TABLES.CASE_FINANCIAL_SUMMARIES).select('support_payout_case_id,currency,requested_minor,paid_minor,prevented_minor,confirmed_loss_minor,recoverable_minor,recovered_minor,written_off_minor,updated_at').eq('merchant_id',merchantId).in('support_payout_case_id',caseIds):{data:[]};
  const financial=(financialData??[]) as Array<Record<string,any>>; const bridges=aggregateMoneyBridges(financial);
  const financialByCase=new Map(financial.map(r=>[r.support_payout_case_id,r])); const causesMap=new Map<string,RankedRow>();
  for(const c of cases){const f=financialByCase.get(c.id);const currency=String(f?.currency||c.currency||'Unknown').toUpperCase();const key=c.reason_normalized||c.claim_type||'unclassified';addRank(causesMap,key,String(key).replaceAll('_',' '),Number(f?.confirmed_loss_minor||0),currency,`/reports/records?kind=case&dimension=reason&value=${encodeURIComponent(key)}&range=${range}&currency=${currency}`)}
  const statuses=new Map<string,number>();for(const c of cases)statuses.set(c.status,(statuses.get(c.status)??0)+1);
  const {data:recoveryData}=await client.from(TABLES.RECOVERY_CASES).select('id,status,recovery_type,currency,merchant_loss_amount,amount_recovered,updated_at').eq('merchant_id',merchantId).limit(10000);const recoveryMap=new Map<string,RankedRow>();
  for(const r of (recoveryData??[]) as Array<Record<string,any>>){if(cutoff&&r.updated_at<cutoff)continue;const currency=String(r.currency||'Unknown').toUpperCase();addRank(recoveryMap,r.status||'unknown',String(r.status||'unknown').replaceAll('_',' '),Math.round(Number(r.amount_recovered||0)*100),currency,`/reports/records?kind=recovery&dimension=status&value=${encodeURIComponent(r.status||'unknown')}&range=${range}&currency=${currency}`)}
  const coverageSpecs=[[TABLES.SOURCE_ORDERS,'Orders','/orders'],[TABLES.SOURCE_TICKETS,'Tickets','/tickets'],[TABLES.SOURCE_SHIPMENTS,'Shipments','/shipments'],[TABLES.SOURCE_REFUNDS,'Refunds','/refunds'],[TABLES.SOURCE_RETURNS,'Returns','/returns'],[TABLES.MERCHANT_CLAIMS,'Payout cases','/claims']] as const;const staleBefore=new Date(Date.now()-48*3600000).toISOString();const coverage:CoverageRow[]=[];
  for(const [table,objectType,href] of coverageSpecs){const date=table===TABLES.SOURCE_REFUNDS?'ingested_at':'updated_at';const [all,fresh,latest]=await Promise.all([client.from(table).select('id',{count:'exact',head:true}).eq('merchant_id',merchantId),client.from(table).select('id',{count:'exact',head:true}).eq('merchant_id',merchantId).gte(date,staleBefore),client.from(table).select(`id,${date}`).eq('merchant_id',merchantId).order(date,{ascending:false}).limit(1)]);const records=all.count??0;const freshRecords=fresh.count??0;coverage.push({objectType,records,freshRecords,staleRecords:Math.max(0,records-freshRecords),latestAt:(latest.data as Array<Record<string,any>>|null)?.[0]?.[date]??null,href})}
  const issues:string[]=[];const invalidCurrencyRows=financial.filter(row=>!normaliseCurrencyOrNull(row.currency)).length;if(invalidCurrencyRows)issues.push(`${invalidCurrencyRows} financial record${invalidCurrencyRows===1?' has':'s have'} a missing or invalid currency and ${invalidCurrencyRows===1?'was':'were'} excluded`);for(const b of bridges){if(b.paidMinor>b.requestedMinor&&b.requestedMinor>0)issues.push(`${b.currency}: paid compensation exceeds requested amount`);if(b.recoveredMinor>b.recoverableMinor&&b.recoverableMinor>0)issues.push(`${b.currency}: recovered exceeds recoverable amount`)}
  return{range,timezone,generatedAt:new Date().toISOString(),bridges,causes:[...causesMap.values()].sort((a,b)=>b.amountMinor-a.amountMinor||b.count-a.count),operations:[...statuses].map(([key,count])=>({key,label:key.replaceAll('_',' '),count,href:`/reports/records?kind=case&dimension=status&value=${encodeURIComponent(key)}&range=${range}`})).sort((a,b)=>b.count-a.count),recoveries:[...recoveryMap.values()].sort((a,b)=>b.amountMinor-a.amountMinor||b.count-a.count),coverage,reconciliation:{ok:issues.length===0,issues},recordCount:cases.length};
}

export const REPORT_DEFINITIONS=[
  {id:'financial',name:'Financial performance',definition:'Ledger amounts by payout-case period and ISO currency.',numerator:'Sum of each canonical financial entry category.',denominator:'Not applicable.',timeBasis:'Payout case submitted in selected period.'},
  {id:'loss-causes',name:'Loss causes',definition:'Realised loss grouped by normalised request reason.',numerator:'Confirmed loss in each reason.',denominator:'All confirmed loss in the same currency and period.',timeBasis:'Payout case submitted in selected period.'},
  {id:'prevention',name:'Payout prevention',definition:'Requested payout recorded as prevented by a merchant decision.',numerator:'Prevented payout.',denominator:'Requested payout in the same currency.',timeBasis:'Payout case submitted in selected period.'},
  {id:'recovery',name:'Recovery performance',definition:'Recovered and outstanding amounts by recovery status.',numerator:'Reconciled recovered amount.',denominator:'Recoverable amount in the same currency.',timeBasis:'Recovery updated in selected period.'},
  {id:'policy',name:'Policy effectiveness',definition:'Recorded merchant decisions grouped by policy result.',numerator:'Cases with the selected recorded result.',denominator:'Cases with a recorded policy result.',timeBasis:'Payout case submitted in selected period.'},
  {id:'operations',name:'Operations / SLA',definition:'Payout-case workload grouped by canonical state.',numerator:'Cases in each state.',denominator:'All cases in the selected period.',timeBasis:'Payout case submitted in selected period.'},
  {id:'evidence',name:'Evidence gaps',definition:'Cases whose canonical workflow state identifies missing or awaited evidence.',numerator:'Cases in evidence-waiting states.',denominator:'Open cases in the selected period.',timeBasis:'Payout case submitted in selected period.'},
  {id:'coverage',name:'Source coverage',definition:'Imported object records and freshness by object family.',numerator:'Records refreshed in the last 48 hours.',denominator:'All imported records in the merchant projection.',timeBasis:'Current source projection.'},
] as const;
