import type { ClaimDecisionContext } from '@/lib/claims/decision/types';

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object | null ? Partial<NonNullable<T[K]>> | null : T[K] };

/** Builds a ClaimDecisionContext with sensible defaults for payout-layer unit tests. */
export function makeContext(overrides: DeepPartial<ClaimDecisionContext> = {}): ClaimDecisionContext {
  const base: ClaimDecisionContext = {
    merchantId: 'merchant-1',
    claim: {
      id: 'claim-1',
      type: 'item_not_received',
      status: 'open',
      amountAtRisk: 80,
      currency: 'GBP',
      reasonRaw: null,
      reasonNormalized: null,
      sourceOrderId: 'order-1',
      sourceTicketId: 'ticket-1',
      identityId: 'identity-1',
      createdAt: '2026-06-10T00:00:00.000Z',
    },
    ticket: {
      id: 'ticket-1',
      externalId: 'GOR-1',
      source: 'gorgias',
      status: 'open',
      subject: 'Package never arrived',
      claimTypeConfidence: 0.9,
    },
    order: {
      id: 'order-1',
      externalId: 'AU-1',
      orderNumber: 'AU-1',
      totalAmount: 80,
      currency: 'GBP',
      createdAt: '2026-05-20T00:00:00.000Z',
      financialStatus: 'paid',
      fulfillmentStatus: 'delivered',
    },
    delivery: {
      status: 'delivered',
      carrier: 'Royal Mail',
      trackingNumber: 'RM1',
      trackingUrl: null,
      deliveredAt: '2026-06-01T00:00:00.000Z',
      hasTracking: true,
      hasProofOfDelivery: true,
      daysSinceDelivery: 9,
    },
    identity: {
      id: 'identity-1',
      confidenceGrade: 'probable',
      confidenceScore: 72,
      evidenceScore: 30,
      evidenceLevel: 'some',
      hasSufficientData: true,
      evidenceBreakdown: null,
      isNetworkFlagged: false,
    },
    history: {
      merchantClaimCount: 3,
      merchantPriorClaimCount: 2,
      merchantSameTypeClaimCount: 3,
      merchantPriorSameTypeClaimCount: 2,
      networkClaimCount: 3,
      networkSameTypeClaimCount: 3,
      priorApprovedClaims: 1,
      priorDeniedClaims: 1,
      priorEscalatedClaims: 0,
      priorChargebacksAfterClaims: 0,
      priorLossOutcomes: 1,
      priorRecoveredOutcomes: 0,
      daysSinceLastClaim: 45,
      claimTypes: ['item_not_received'],
      hasCrossMerchantIdentity: false,
      networkMerchantCount: 1,
      accountAgeDays: 400,
    },
    evidence: {
      totalEvidenceItems: 1,
      customerEvidenceItems: 1,
      deliveryEvidenceItems: 0,
      merchantEvidenceItems: 0,
      hasCustomerEvidence: true,
      hasDeliveryEvidence: false,
    },
  };

  return {
    ...base,
    ...('merchantId' in overrides ? { merchantId: overrides.merchantId as string } : {}),
    claim: { ...base.claim, ...(overrides.claim ?? {}) },
    ticket: overrides.ticket === null ? null : { ...base.ticket!, ...(overrides.ticket ?? {}) },
    order: overrides.order === null ? null : { ...base.order!, ...(overrides.order ?? {}) },
    delivery: overrides.delivery === null ? null : { ...base.delivery!, ...(overrides.delivery ?? {}) },
    identity: overrides.identity === null ? null : { ...base.identity!, ...(overrides.identity ?? {}) },
    history: { ...base.history, ...(overrides.history ?? {}) },
    evidence: { ...base.evidence, ...(overrides.evidence ?? {}) },
  };
}
