import Anthropic from '@anthropic-ai/sdk'

const client = new Anthropic()

export interface EvaluationResult {
  passed: boolean
  score: number
  findings: string[]
  suggestions: string[]
  rawReasoning: string
}

export interface PageEvaluation {
  pageDescription: string
  extractedText: string
  screenshotBase64?: string
}

function hardFailIfBanned(text: string): EvaluationResult | null {
  const lower = text.toLowerCase()
  if (/\bfraud\b/.test(lower)) {
    return {
      passed: false,
      score: 0,
      findings: ['Merchant-facing copy contains the banned word "fraud"'],
      suggestions: [],
      rawReasoning: 'Local hard-rule precheck failed before AI evaluation.'
    }
  }
  return null
}

export async function evaluateMerchantExperience(
  page: PageEvaluation,
  criteria: string[]
): Promise<EvaluationResult> {
  const hardFail = hardFailIfBanned(page.extractedText)
  if (hardFail) return hardFail

  const prompt = `You are evaluating a page from Unauth, a fraud intelligence application for ecommerce merchants.

The merchant using this app is non-technical. They run an ecommerce store and are trying to identify customers who may be using multiple accounts to abuse their refund policy. They are not a developer. They should not need to understand technical concepts to use this product.

Page being evaluated: ${page.pageDescription}

Page text content:
${page.extractedText}

Evaluation criteria — check each one explicitly:
${criteria.map((c, i) => `${i + 1}. ${c}`).join('\n')}

CRITICAL CONTENT RULES — these are non-negotiable and must be checked on every evaluation:
- The word "fraud" must NEVER appear in merchant-facing copy. Flag immediately if found.
- Technical jargon (entity resolution, confidence score, signal, heuristic, algorithm, normalisation, hash) must not appear in merchant-facing text. Flag immediately if found.
- No other merchant or company must be named anywhere. Flag immediately if found.
- Confidence grades must use exactly these terms: Definite, Probable, Possible, Weak — nothing else.
- Any empty state must explain what the page does and provide a clear next action.

Respond with a JSON object in this exact format:
{
  "passed": boolean,
  "score": number between 0 and 100,
  "findings": ["specific issue 1", "specific issue 2"],
  "suggestions": ["improvement 1", "improvement 2"],
  "rawReasoning": "your full reasoning"
}

Be specific. Do not say "the page could be clearer" — say "the heading 'Identity Verification' on line 3 uses technical language that a non-technical merchant would not understand. Replace with 'Customer matching results'."

If passed is false, findings must contain at least one item explaining exactly why.`

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1500,
    messages: [{ role: 'user', content: prompt }]
  })

  const text = response.content[0].type === 'text' ? response.content[0].text : ''

  try {
    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No JSON found in response')
    const parsed = JSON.parse(jsonMatch[0]) as EvaluationResult
    return hardFailIfBanned(page.extractedText) ?? parsed
  } catch {
    return {
      passed: false,
      score: 0,
      findings: ['AI evaluator failed to parse response — manual review required'],
      suggestions: [],
      rawReasoning: text
    }
  }
}

export async function evaluatePDFContent(
  pdfText: string,
  referenceNumber: string
): Promise<EvaluationResult> {
  const hardFail = hardFailIfBanned(pdfText)
  if (hardFail) return hardFail

  const prompt = `You are evaluating a chargeback evidence PDF generated by Unauth.

This PDF will be submitted by a merchant to their bank or payment processor as evidence in a chargeback dispute. It must meet strict professional and content standards.

PDF text content:
${pdfText}

Check every one of these rules explicitly:

HARD RULES — any failure here means passed: false immediately:
1. The word "fraud" must NOT appear anywhere in the document — not in headings, not in body copy, not in footers, not in labels
2. No other merchant's name must appear anywhere
3. No other merchant's customer data must be referenced
4. The reference number must match the format UNAUTH-YYYYMMDD-NNNNNN — check: ${referenceNumber}
5. The document must contain a narrative summary section
6. The document must contain an order history table
7. The document must contain an identity evidence section
8. The footer must include the Unauth URL and reference number

QUALITY RULES — failures here reduce the score but may not fail the test:
9. The narrative must be written in plain English suitable for a bank dispute reviewer
10. All PII must be masked (emails show first char, ****, last char before @domain)
11. CE3.0 section must state clearly whether eligible or not and give a reason
12. The document must look professional — structured sections, clear headings

Respond with JSON in this exact format:
{
  "passed": boolean,
  "score": number,
  "findings": ["specific issue with exact quote from document if applicable"],
  "suggestions": [],
  "rawReasoning": "full reasoning"
}`

  const response = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 1500,
    messages: [{ role: 'user', content: prompt }]
  })

  const text = response.content[0].type === 'text' ? response.content[0].text : ''

  try {
    const jsonMatch = text.match(/\{[\s\S]*\}/)
    if (!jsonMatch) throw new Error('No JSON found in response')
    const parsed = JSON.parse(jsonMatch[0]) as EvaluationResult
    return hardFailIfBanned(pdfText) ?? parsed
  } catch {
    return {
      passed: false,
      score: 0,
      findings: ['PDF evaluator failed to parse response'],
      suggestions: [],
      rawReasoning: text
    }
  }
}

export function assertEvaluation(
  result: EvaluationResult,
  context: string,
  minimumScore = 70
) {
  if (!result.passed) {
    throw new Error(
      `AI evaluation FAILED for: ${context}\n` +
      `Score: ${result.score}/100\n` +
      `Findings:\n${result.findings.map(f => `  - ${f}`).join('\n')}\n` +
      `Reasoning: ${result.rawReasoning}`
    )
  }
  if (result.score < minimumScore) {
    throw new Error(
      `AI evaluation BELOW THRESHOLD for: ${context}\n` +
      `Score: ${result.score}/100 (minimum: ${minimumScore})\n` +
      `Findings:\n${result.findings.map(f => `  - ${f}`).join('\n')}`
    )
  }
}
